### ISSUE TITLE
Protocol lib isnt recognized

### ISSUE THREAD

**Issue by Zocker377** [Imprex-Development/orebfuscator#103]
Hi,
i just installed orebfusctor but when i look after the status, it says that protocol-lib not installed is. I installed Protocollib already so what now. Protocol lib version is 4.4.3 and the server is running on spigot 1.16.5

Please help me D:

**Comment by NgLoader** [comment]
This project is not maintained, use Imprex-Development/Orebfuscator

**Comment by NgLoader** [comment]
When you use /plugins is ProtocolLib green?

**Comment by Zocker377** [comment]
Yes

**Comment by Ingrim4** [comment]
Can you please provide us with a screenshot of your `/plugins` and the whole console log so we can investigate this further?

**Comment by Zocker377** [comment]
[2021-06-12-5.log](https://github.com/Imprex-Development/Orebfuscator/files/6643453/2021-06-12-5.log)
![Unbenannt](https://user-images.githubusercontent.com/44677320/121798915-4d726480-cc29-11eb-9467-bfad915c7715.PNG)

**Comment by Ingrim4** [comment]
Looks like your using an old version of OFC, here is the latest release: https://github.com/Imprex-Development/Orebfuscator/releases/tag/5.1.4
