### ISSUE TITLE
World name with spaces - crash

### ISSUE THREAD

**Issue by FluffyDev1** [Imprex-Development/orebfuscator#111]
**Please fill out the following information:**

* Server Version: Paper version git-Paper-"33d6b6f" (MC: 1.17)
* Orebfuscator Version: 5.1.5
* Protocollib Version: 4.6.0

**Describe the bug**

Make a new world with spaces, and try to put  it in the worlds

**Comment by NgLoader** [comment]
I currently cannot reproduce this bug.
Can you please provide an error log?

A minecraft server only allow world names matched by ``[a-z0-9/._-]``
Paper issue https://github.com/PaperMC/Paper/issues/5397

**Comment by FluffyDev1** [comment]
Wait, i get this error:
Error occurred while enabling Orebfuscator v5.1.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketAdapter

**Comment by NgLoader** [comment]
You need to install the latest [protocollib](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) version

**Comment by FluffyDev1** [comment]
i got protocollib

**Comment by NgLoader** [comment]
your protocollib version is 4.6.0 but the latest version is [4.7.0](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

**Comment by FluffyDev1** [comment]
yea thanks
