### ISSUE TITLE
Is there a way to change the engine mode like the original plugin 

### ISSUE THREAD

**Issue by Catogoodmen** [Imprex-Development/orebfuscator#113]
Is there a way to change the engine mode like the original plugin so that it doesn't render all the ores.

![image](https://user-images.githubusercontent.com/86155056/122812857-24597000-d2ca-11eb-8508-0ce5949dc945.png)

**Comment by NgLoader** [comment]
Yea, just edit the config.yml - See: https://github.com/Imprex-Development/Orebfuscator/wiki/Config#world

You need to remove ``stone`` from hiddenblocks and only add ``stone`` to randomblocks
