### ISSUE TITLE
Aristois Legit X-Ray bypasses Orebfuscator X-Ray Protection

### ISSUE THREAD

**Issue by Pledix** [Imprex-Development/orebfuscator#114]
• Server Version: Purpur version git-Purpur-1171 (MC: 1.16.5)
 • Orebfuscator Version: 5.1.4
 • Protocollib Version: 4.6.1-SNAPSHOT-b503

Orebfuscator blocks xray resource packs and normal x-ray but can't block legit x-ray.

Normal X-Ray:
https://imgur.com/A5cJC3e

Legit X-Ray:
https://imgur.com/6Oj1Bv1

**Comment by Ingrim4** [comment]
You can block it if you also hide every ore with the proximity hider. This is caused by the fact that only none visible blocks are obfuscated every other block (e.g. ores at cave walls) are visible. We deliberately choose that setting as to not ruin the mining experience to much.
