### ISSUE TITLE
Does not fuscate ores

### ISSUE THREAD

**Issue by Linus42069** [Imprex-Development/orebfuscator#117]
* Server Version: 1.17.1
* Orebfuscator Version: 5.1.5
* Protocollib Version: 4.7.0

**Describe the bug**

Well basically the ores aren fuscated. When using xray (also being deop after re-logging and re-starting the server) I can clearly see all the ores. *Ive not edited the config*

**How to reproduce**

Install on Orebfuscator 5.1.5 and Protocolib 4.7.0 on a 1.17.1 Tunity server. 

**EDIT:** Forgot to say, when I mine down to them they are "real" ores

**Comment by S4murajGames** [comment]
i have the same problem :(

**Comment by Ingrim4** [comment]
Can't reproduce! Could it maybe be that your world isn't called "world"?

**Comment by Tomauskis** [comment]
> Can't reproduce! Could it maybe be that your world isn't called "world"?

You could mention that in description. Had the same problem.

**Comment by Ingrim4** [comment]
> You could mention that in description

What do you mean? I don't think I need to mention that the default config is only configured for the default world names: world, world_nether, world_the_end. If you had read the wiki page about the config you could have known that: https://github.com/Imprex-Development/Orebfuscator/wiki/Config

**Comment by Tomauskis** [comment]
> What do you mean? I don't think I need to mention that the default config is only configured for the default world names: world, world_nether, world_the_end. If you had read the wiki page about the config you could have known that: https://github.com/Imprex-Development/Orebfuscator/wiki/Config

I didn’t delve into that. I had multiple worlds and curent wasn't the "world", so this plugin didn't work. Discovered this in configuration file just recently.
