### ISSUE TITLE
Creeper explosions don't reload Orebfuscator

### ISSUE THREAD

**Issue by WolfyRed** [Imprex-Development/orebfuscator#118]
**Please fill out the following information:**

* Server Version: git-Paper-655 (MC: 1.13.2)
* Orebfuscator Version: Orebfuscator version 5.1.5
* Protocollib Version: ProtocolLib version 4.7.0

**Describe the bug**

First, get TNT and Flint & Steel, or lure a creeper over to you.
Next, set the TNT off or get really close to the creeper.
The explosion will not update the surrounding blocks like mining does, it uncovers all the fake ores under the ground.

**Comment by Ingrim4** [comment]
If you're talking about the short time between the explosion and the block update where the fake blocks are briefly visible that isn't a bug. This probably happens because paper's explosions are async.

If however you mean fake blocks being permanently visible after an explosion that wouldn't be indented. We can't reproduce that if that would be the case. Should the later be your issue please try to provide more info in regards to your server, like plugins, config and so on.

**Comment by WolfyRed** [comment]
> If you're talking about the short time between the explosion and the block update where the fake blocks are briefly visible that isn't a bug. This probably happens because paper's explosions are async.
> 
> If however you mean fake blocks being permanently visible after an explosion that wouldn't be indented. We can't reproduce that if that would be the case. Should the later be your issue please try to provide more info in regards to your server, like plugins, config and so on.

The problem was being caused by a plugin that lets you get all blocks from an explosion.

**Comment by WolfyRed** [comment]
> If you're talking about the short time between the explosion and the block update where the fake blocks are briefly visible that isn't a bug. This probably happens because paper's explosions are async.
> 
> If however you mean fake blocks being permanently visible after an explosion that wouldn't be indented. We can't reproduce that if that would be the case. Should the later be your issue please try to provide more info in regards to your server, like plugins, config and so on.

And even so, yes, the fake blocks being permanently visible after an explosion was what was occurring. It, however, went away after interacting with the fake ores.

**Comment by NgLoader** [comment]
Please provide us more Information, were currently unable to reproduce you issue
