### ISSUE TITLE
xray can be opened

### ISSUE THREAD

**Issue by ttt0** [Imprex-Development/orebfuscator#120]
**Please fill out the following information:**

* Server Version: ![image](https://user-images.githubusercontent.com/66686400/126979068-535f0000-670d-4e57-9f77-d01a9387f793.png)
* Orebfuscator Version: ![image](https://user-images.githubusercontent.com/66686400/126979122-e1ec3fce-48d1-496e-b866-00ffffad6ea8.png)
* Protocollib Version: ![image](https://user-images.githubusercontent.com/66686400/126979140-145376be-6198-40d2-9cd9-3a1451c05ad0.png)

**xray can be opened**

**Comment by ttt0** [comment]
There is a texturepack in version 1.17.1 called xray ultimate and cheat can be opened

**Comment by NgLoader** [comment]
Do you have the permission ``*`` or ``orebfuscator.bypass``?
Is your currently world in the config.yml?

When this does not solve your issue, please describe it more where the problem is.
