### ISSUE TITLE
Server Operator exclusion list

### ISSUE THREAD

**Issue by fnrcum** [Imprex-Development/orebfuscator#127]
**Describe your feature**
A simple list to exclude the server operators from being affected by the obfuscator.

**Comment by Ingrim4** [comment]
We don't plan on adding a list of players that can bypass orebfuscator. We do however have a permission to bypass obfuscation called: `orebfuscator.bypass`.

**Comment by fnrcum** [comment]
This is perfect, I just needed a way to debug stuff without having to take down the server and deactivate it first
