### ISSUE TITLE
an internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by steakperson** [Imprex-Development/orebfuscator#128]
when i try to do all of the orebfuscator commands such as /ofc reload, /ofc status etc it comes up with an internal error occurred while attempting to perform this command.
please help how do i fix this.

**Comment by Ingrim4** [comment]
As of now we currently haven't implemented or registered any commands. Could you maybe have used an extremely old version of Orebfuscator? The latest version can be found here: https://github.com/Imprex-Development/Orebfuscator/releases/latest
