### ISSUE TITLE
Feature: do not reveal proximity blocks to spectators

### ISSUE THREAD

**Issue by heathfx** [Imprex-Development/orebfuscator#129]
**Describe your feature**
When a player is in spectate mode, add an option to never show blocks that are hidden by the proximity hider.

**why?**
I want to allow my users to spectate, but they get teleported back to their original position when exiting spectate mode. The problem is that this would allow them to easily search for exposed ore. If I could make it so proximity hidden ores are never exposed to spectators, then I could add a great feature to my server.

**Comment by Ingrim4** [comment]
This is something I see myself adding in the next update. Unfortunately I'm as of now short on time which is why it could be a while until the next update. However your welcome to contribute to Orebufscator yourself.
