### ISSUE TITLE
OREBFUSCATOR LAG PROBLEM

### ISSUE THREAD

**Issue by giantfurkii** [Imprex-Development/orebfuscator#132]
The orebfuscator plug-in puts my server in the lag.
https://timings.aikar.co/?id=9e5b2770668049888d9a744f62a85b9c#plugins

**Comment by NgLoader** [comment]
Please use an [issue template](https://github.com/Imprex-Development/Orebfuscator/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and fill out the informations in there.
So we can understand and handle your issue better!

When you permanently generate new chunk it is normal that ofc need more power to obfuscate the chunks but when you have enabled the cache ofc don't need to do that every time only when a new chunk is generated or a currently chunk is invalied

**Comment by giantfurkii** [comment]
https://github.com/Imprex-Development/Orebfuscator/issues/133
