### ISSUE TITLE
ProtocolLib Missing

### ISSUE THREAD

**Issue by affo5** [Imprex-Development/Orebfuscator#136]
I was trying to get orebfuscator on my smp server hosted by apex server hosting. I made the server spigot 1.17 but it says ProtocolLib is missing. I put it in the plugins directory so I'm not sure whats the problem

**Comment by affo5** [comment]
I'm using an xray texture pack right now and I can see all ores perfectly fine I cant figure out why

**Comment by affo5** [comment]
![image](https://user-images.githubusercontent.com/92095946/136383678-bcaa851f-bd2b-4006-afa6-c4a5dac09f40.png)

**Comment by affo5** [comment]
ok now I have downloaded it correctly I think but I'm not sure how to use it. I can't seem to find the problem. I downloaded latest version of ProtocolLib and Orebfuscator. Now I'm not sure why it's not working it's in my plugins folder but the x-ray still works. Do I have to change things in the config or something? Also I'm using apex server hosting so please tell me how to set it up.

**Comment by Ingrim4** [comment]
See: https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated
