### ISSUE TITLE
Zip file

### ISSUE THREAD

**Issue by Frolijk** [Imprex-Development/orebfuscator#137]
**Please fill out the following information:**

* Server Version: This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) 
* Orebfuscator Version:  I can't install it.
* Protocollib Version:  Same as above

**Describe the bug**
Hey i just wanted to put the plugin into my server but it wont work when i put it straight in and restart.
How can i fix this?

**Comment by Ingrim4** [comment]
Are there any errors in the console when you try to start your server with OFC.

**Comment by NgLoader** [comment]
You need to download the spigot version from the original [spigot page](https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/) or [github releases page](https://github.com/Imprex-Development/Orebfuscator/releases)

When you use a dashboard where you can install plugins it will possible failing!
