### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by affo5** [Imprex-Development/orebfuscator#141]
I'm not sure how to bypass the obfuscator. I am an operator with access to the server files so how do I add myself to the list of not getting obfuscated?

**Comment by NgLoader** [comment]
[Wiki Permission](https://github.com/Imprex-Development/Orebfuscator/wiki/Permissions)

**Comment by affo5** [comment]
So this is saying that I can't bypass it. So if I can't, Who can? I also have access to the server console
Do I have to add myself to a list in the config or something.

**Comment by affo5** [comment]
![image](https://user-images.githubusercontent.com/92095946/140824962-37ee200c-bc3b-4b13-b037-7e179effbee6.png)

**Comment by affo5** [comment]
im the owner

**Comment by affo5** [comment]
it also says orebfuscator.admin is allowed in op but how do I use it

**Comment by Ingrim4** [comment]
You need the `orebfuscator.bypass` permission in order to bypass obfuscation. This permission is not set for *op* players by default.

**Comment by affo5** [comment]
so how do i set it for myself? and also if ops don't have access to it who does?

**Comment by CodingLars** [comment]
That depends on what permission plugin you are using. If you use LuckPerms, then google how to set/unset permissions with it. 
No one has access to it, if you haven't given anyone access to it.
