### ISSUE TITLE
Chunks wont load even after removing plugin

### ISSUE THREAD

**Issue by LeonTheDev-io** [Imprex-Development/orebfuscator#143]
* Server Version: git-paper-790 MC 1.16.5 
* Orebfuscator Version: 5.1.6
* Protocollib Version: 4.7.0

**Describe the bug**

Hey, so I changed the random blocks in the config all to Minecraft:diamond_block, after /reloading the plugin the whole world disappeared, and even removing the plugin won't fix it.

**Comment by LeonTheDev-io** [comment]
![image](https://user-images.githubusercontent.com/82466943/144104230-af877e81-1fee-42ba-8aa2-dbd7d98cda7a.png)

It looks like that... when I place sometihng it loads a few blocks near in

**Comment by Ingrim4** [comment]
If you remove the plugin and it still doesn't work then it's not the plugins fault.

**Comment by LeonTheDev-io** [comment]
My bad, just restarted Minecraft and it worked, Minecraft issue.
