### ISSUE TITLE
On the latest version, you can see ores through non-full blocks 

### ISSUE THREAD

**Issue by ghost** [Imprex-Development/orebfuscator#148]
On the latest version of orebfuscator on 1.18, you can see the ores used to block xray through the corner of stairs
![image](https://user-images.githubusercontent.com/72661987/144468320-9d2a485f-ed1f-4be7-8fbd-e65ac7936437.png)

**Comment by ToastedEggplant** [comment]
Ah, I was writing up my issue at the same time this was posted, nice.

**Comment by Ingrim4** [comment]
Duplicate of #149
