### ISSUE TITLE
Snowy Mountains do not seem to play well with Orebfuscator

### ISSUE THREAD

**Issue by ToastedEggplant** [Imprex-Development/orebfuscator#149]
**Please fill out the following information:**

* Server Version:3339-Spigot-3c40a6c-581df18 MC 1.18
* Orebfuscator Version: 5.2.0 
* Protocollib Version: 4.8.0-SNAPSHOT-B538

**Mountains do not seem to play well with Orebfuscator**

 Heading over to snowy mountains and some of the non snowy mountains will produce this. I don't think blocks behind snow should be obfuscated. Maybe there's a config for this I'm not aware of but even if so I wanted to make sure this was documented. 
![mountain3](https://user-images.githubusercontent.com/9472512/144472684-89ea4eaf-056b-4d5a-9408-f0f6849c86a2.jpg)
![mountain1](https://user-images.githubusercontent.com/9472512/144472685-15f739de-f5a1-4235-bfea-64c6036a2a30.jpg)
![mountain4](https://user-images.githubusercontent.com/9472512/144472688-880d27bc-287f-4b1a-aa30-37d3f0b4f51d.jpg)
![mountain5](https://user-images.githubusercontent.com/9472512/144472691-d27115aa-0c4c-45e5-808a-1a0a4dddb6e8.jpg)
![mountain2](https://user-images.githubusercontent.com/9472512/144472692-6a35bfbf-4971-4d82-b63c-00faf25f0698.jpg)

**Comment by GreenDragon1612** [comment]
bro how do you add orebfuscator to your world? it doesnt work on my Server

**Comment by ghost** [comment]
I think this is the same issue I'm facing

**Comment by ToastedEggplant** [comment]
> bro how do you add orebfuscator to your world? it doesnt work on my Server

Assuming you have spigot installed you can get the plugin [here ](https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/) and there are also instructions on that page on how to install it!

**Comment by ToastedEggplant** [comment]
> I think this is the same issue I'm facing

If you have any other instances of the issue feel free to post them for documentation!

**Comment by GreenDragon1612** [comment]
> > bro how do you add orebfuscator to your world? it doesnt work on my Server
> 
> Assuming you have spigot installed you can get the plugin [here ](https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/) and there are also instructions on that page on how to install it!

I have Spigot installed and it doesnt work anyways.
![Bild_2021-12-02_184352](https://user-images.githubusercontent.com/95433630/144475261-9a1758b7-9990-44ce-8220-ee78e26f14e7.png)

**Comment by GreenDragon1612** [comment]
> > bro how do you add orebfuscator to your world? it doesnt work on my Server
> 
> Assuming you have spigot installed you can get the plugin [here ](https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/) and there are also instructions on that page on how to install it!

[18:48:58] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.2.0
[18:48:58] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.8.0-SNAPSHOT-b538

thats what the consol says

**Comment by Ingrim4** [comment]
I think I know what the problem is, let me do some testing and I will probably have this fixed today.

**Comment by ToastedEggplant** [comment]
> I think I know what the problem is, let me do some testing and I will probably have this fixed today.

Awesome! Thank you!
