### ISSUE TITLE
It doesnt show fake blocks when using a xray texturepack

### ISSUE THREAD

**Issue by EasternAirTemple** [Imprex-Development/orebfuscator#150]
**Please fill out the following information:**

* Server Version: 
* Orebfuscator Version: 
* Protocollib Version: 

**Describe the bug**

**Comment by Ingrim4** [comment]
Have you tried this: https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated

**Comment by EasternAirTemple** [comment]
Thank you for responding i will try these things as soon as possible

**Comment by NickelWW** [comment]
Make sure you have the right world name in the config file! That was the issue for me.
