### ISSUE TITLE
add the plugin to site

### ISSUE THREAD

**Issue by US861** [Imprex-Development/orebfuscator#152]
Please add the plugin to www.spigotmc.org.  I use Aternos hosting and cannot download to my server because the hosting only supports certain sites like spigotmc.org.  If you add, I will be very grateful!

**Comment by molor** [comment]
wat
![image](https://user-images.githubusercontent.com/19989717/144746553-515b6729-2b2b-4993-bbdb-580611404b1d.png)

**Comment by US861** [comment]
> Wat ![изображение](https://user-images.githubusercontent.com/19989717/144746553-515b6729-2b2b-4993-bbdb-580611404b1d.png)

![IMG_20211205_163359](https://user-images.githubusercontent.com/59504323/144748693-d6b545ff-e7cb-4fae-b289-89f557d1564f.jpg)

**Comment by molor** [comment]
OMG, I'm sorry, didn't pay attention
