### ISSUE TITLE
New Feature Suggestions

### ISSUE THREAD

**Issue by US861** [Imprex-Development/orebfuscator#153]
Hello, while I was testing this plugin on my local network, I came up with some additions to this plugin.  1) So that it generates non-existent chests.  2) Raise the optimization a little (when the user looks down, the FPS drops by 20-30).  Thank you for the attention!

**Comment by NgLoader** [comment]
https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#users-experience-low-fps

**Comment by US861** [comment]
> https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#users-experience-low-fps

Oh good.  what about chests?

**Comment by NgLoader** [comment]
What did you mean with cheats?
