### ISSUE TITLE
Ore's are shown on surface | Bug?

### ISSUE THREAD

**Issue by striiki** [Imprex-Development/orebfuscator#155]
Ye i got a picture to show you 

i mean... its like: 
![2021-12-09_11 28 58](https://user-images.githubusercontent.com/95854612/145379837-5181503c-35bb-4445-85b8-32f40ca2a49f.png)

i tried to change it in the config but it didn't work:
-------------
proximity:
- enabled: true
  worlds:
  - world
  distance: 24
  useFastGazeCheck: false
  defaults:
    y: 70
    above: false
    useBlockBelow: true
---------------
Thank You ! :)

**Comment by striiki** [comment]
Server Version: 1.17.1 Spigot
Orebfuscator Version: 5.2.1
Protocollib Version: newest

**Comment by Ingrim4** [comment]
Are you sure you're using OFC 5.2.1 because this should have been fixed in 5.2.1?

**Comment by Ingrim4** [comment]
Please also try to the delete your (orebfuscator) cache because I'm pretty sure I forgot to add the plugin version to the cache hash.

**Comment by striiki** [comment]
Ye 100% sure that im using 5.2.1

**Comment by striiki** [comment]
you mean the hole folder or just the inside of the folder?

**Comment by striiki** [comment]
okay after deleting the cache folder it  worked thank you

**Comment by Ingrim4** [comment]
Created an issue where I will fix the cache not clearing on plugin version change: #156 
Thank you for reporting that.
