### ISSUE TITLE
1.18 fps drops

### ISSUE THREAD

**Issue by Comitant** [Imprex-Development/orebfuscator#158]
Running default Orebfuscator on my 1.18 server almost halves player fps. I'm not sure if this is a bug or something that is unfixable, but the frame drops are really bad.

Using the latest version of orebfuscator and protocollib.

**Comment by Ingrim4** [comment]
See: https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#users-experience-low-fps

**Comment by Comitant** [comment]
> See: https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#users-experience-low-fps

Yep that did the trick, thank you! Didn't read that before since I was in a hurry with how many people it was affecting.
