### ISSUE TITLE
Jukebox not works

### ISSUE THREAD

**Issue by Kr1S-D** [Imprex-Development/Orebfuscator#161]
It doesn't blur blocks like jukeboxes

**Comment by NgLoader** [comment]
You need to add ``minecraft:jukebox`` to ``hiddenBlocks`` into your config.

Checkout: [Config](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section)

**Comment by Kr1S-D** [comment]
for stained_clay:0 ?

**Comment by NgLoader** [comment]
what did you exactly mean?
When you wan't to know how the item is named, press ``F3 + H`` to toggle tooltips and hover over the item.

**Comment by Kr1S-D** [comment]
[stained clay](https://minecraftuniverse.fandom.com/wiki/White_Stained_Clay)

**Comment by Kr1S-D** [comment]
i m in 1.12.2

**Comment by NgLoader** [comment]
Use ``stained_clay: 1``

**Comment by Kr1S-D** [comment]
`randomBlocks:`
    `stained_clay: 1: 5`

**Comment by Kr1S-D** [comment]
right?

**Comment by Kr1S-D** [comment]
in randomblocks jukebox doesn't work

**Comment by Kr1S-D** [comment]
[(https://pastebin.com/8ptbxfeR)](https://pastebin.com/iuKxmwpc)

**Comment by Kr1S-D** [comment]
wheere is the erorr?

**Comment by Kr1S-D** [comment]
he removes the clay
and the jukebox in randomblocks

**Comment by Kr1S-D** [comment]
so i fixed it but in legacy version
cause "unable to locate sign at (x,y,z) to legacy clients !!! can u solve this?
"

**Comment by Kr1S-D** [comment]
https://www.spigotmc.org/attachments/error-png.1872/

**Comment by Kr1S-D** [comment]
similar to this

**Comment by NgLoader** [comment]
Can you please share your config?

**Comment by Ingrim4** [comment]
closed due to inactivity
