### ISSUE TITLE
plugin is not working

### ISSUE THREAD

**Issue by ItzDaster** [Imprex-Development/orebfuscator#162]
server version: 1.18.1
Orebfuscator version: 5.2.1
protocollib version: 4.7.0

Hello, I need help because the plugin doesn't work I was testing it on resource pack x-ray ultimate and it worked normally the plugin didnt hide the blocks.
What should I do?
Already readed the the issues.

**Comment by NgLoader** [comment]
[Wiki Common-Issues](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues)

This could have many reasons so here is a short checklist to see if you did anything wrong:

- Check that the player doesn't have the orebfuscator.bypass permission
- Check if you have installed the latest version of Orebfuscator and ProtocolLib for your game version
- Check if there are any warnings in the console about a wrongly configured config
- Check if you used the correct world names in the config

**Comment by Ingrim4** [comment]
closed due to inactivity
