### ISSUE TITLE
Obfuscation does not work on 1.18 on layers below Y=0

### ISSUE THREAD

**Issue by fabegalo** [Imprex-Development/orebfuscator#169]
![image](https://user-images.githubusercontent.com/53371411/147861744-1e9ee5a5-9a08-4366-b377-809336fd29af.png)

**Please fill out the following information:**

* Server Version: Purpur version git-Purpur-1459 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)  
* Orebfuscator Version: Orebfuscator version 5.2.2
* Protocollib Version: ProtocolLib version 4.7.0 

**Describe the bug**

Obfuscation does not work on 1.18 on layers below Y=0

Same minY: -2032 in the configuration it only works until Y=0

**Comment by Ingrim4** [comment]
Have you tried deleting the config and if that doesn't fix it then please provide your config (not the default one) as [pastebin](https://pastebin.com/).

**Comment by fabegalo** [comment]
> Have you tried deleting the config and if that doesn't fix it then please provide your config (not the default one) as [pastebin](https://pastebin.com/).

Thanks, deleting the old configuration starts to work perfectly, but the default configuration comes with many blocks, bedrocks players have a lot of lag in this configuration, I'll see how I can adjust it to generate blocks in smaller amounts, thanks :D
