### ISSUE TITLE
Chunks not loading?

### ISSUE THREAD

**Issue by CombatMedic02** [Imprex-Development/orebfuscator#170]
Hello, after updating to the new version of this plugin, 5.2.2, I am having the chunks not loading problem. This normally happens on login or after using a teleport command. Until I relog nothing loads. Before updating to this version when I teleported occasionally chunks would stop loading until I relogged.

My ProtocolLib is Dev Build #540 (2nd Jan) and I'm running Paper-1.18.1-117.

I'm not getting any console warnings or errors. I'll post screenshots next time it happens if needed.

What do I need to do to fix this issue? I read something about needing to turn something off in the paper config? What/where is that?/Does this apply to my problem?

![nochunks](https://user-images.githubusercontent.com/1338330/147893608-0d4aaa84-e71a-4b58-bd67-4c10352e4ad4.png)

**Comment by ghost** [comment]
same here (1.17.1 paper using latest version of this plugin), but i saw this error: https://pastebin.com/zHYafex8

**Comment by Ingrim4** [comment]
The error is related to the issue but only on version before 1.18, because this error can only occur on such versions and would cause chunk packets to get lost. This in turn would cause the client to not render chunks. Will fix that asap (for version before 1.18 in #171). Still not sure what the problem with 1.18 is though.

**Comment by CombatMedic02** [comment]
Yeah, it's weird, I'm not getting any errors or warnings though. Maybe they're connected somehow? Just wanted to let you know that it still happens in Paper 1.18-177. I'll let you know if updating either paper or ProtocolLib fixes the issue as that is what I'll try first once new builds are available.

**Comment by Ingrim4** [comment]
Could you try if this fixed it for you: https://github.com/Imprex-Development/Orebfuscator/suites/4878107752/artifacts/139481868 (source: https://github.com/Imprex-Development/Orebfuscator/tree/test-fix-for-chunk-not-loading)

**Comment by CombatMedic02** [comment]
Thanks Ingrim, I'll put this version on my server and will let you know if it helps. :)

**Comment by CombatMedic02** [comment]
Unfortunately the problem still persists. The best way to reproduce it is to teleport to spawn after being quite far away from it. I find that always seems to get me stuck in the void.

I had played for almost 4 hours with out it happening though so perhaps you're on the right track? But yeah, teleporting still seems to be an issue occasionally, the world just doesn't load after teleporting.

**Comment by Ingrim4** [comment]
So this did improve it though right? If that's the case then ProtocolLib is to blame (probably maybe). My last idea would be to ditch ProtocolLib and see how far that get's me but that would mean implementing a budget version of protocollib for every version from 1.9 - 1.18 so I would rather not. Might try this with 1.18 only and see if that fixes it for you and if that's the case I'm gone see if this is something that can be fixed in cooperation with the ProtocolLib dev.

**Comment by CombatMedic02** [comment]
It feels better. From what I played tonight anyway. But yeah, teleporting still causes the world not to load now and again until you log out and back in again (sometimes fixes it, sometimes doesn't) or teleport somewhere else then teleport back a couple of times.

I appreciate the hard work dude. I don't think any other anti-xray comes close to this one, the fact that you're so dedicated to keeping it running is awesome and very much appreciated.

**Comment by Ingrim4** [comment]
Just got a dumb idea, will try to not use async protocollib and see if it's a problem with the async pipeline.

**Comment by CombatMedic02** [comment]
Just thought of something else. It couldn't be some sort of conflict with the built in anti-xray that paper has could it? I read something about disabling a cache if using this plugin with paper but I couldn't find out how. It didn't really seem like people were sure about it either. They weren't sure if it causes problems or not since they use different methods of hiding the ore or something.

**Comment by Ingrim4** [comment]
You can just disable the cache in the config through setting cache.enabled to false. Here is a version without async protocollib: https://github.com/Imprex-Development/Orebfuscator/suites/4891084911/artifacts/140233717

P.S. Might be easier to communicate over discord just add me: Maurice#7519
