### ISSUE TITLE
Chunk problem

### ISSUE THREAD

**Issue by ZappySK** [Imprex-Development/orebfuscator#175]
Hello, I am using WildTools on my server, where is 3x3 Pickaxes which breaks 3x3 hole, so my problem is that when players are using this pickaxes, they see this, can you fix this or how can i prevent this?
![image](https://user-images.githubusercontent.com/76651966/148687734-ebb357e0-368b-49f0-9948-aee1ce13530f.png)

**Comment by ZappySK** [comment]
When they hit the diamond, it dissapear, so I need to fix this, how?

**Comment by ZappySK** [comment]
https://bg-software.com/wildtools/

**Comment by Ingrim4** [comment]
As far as I know `WildTools` would need to hook themself in our API for this to work. If this is something you need you could implement this yourself or try asking the `WildTools` devs if this is something they would want to do.
