### ISSUE TITLE
chests and other vaults

### ISSUE THREAD

**Issue by Demandss** [Imprex-Development/orebfuscator#176]
* Server Version: 1.17.1 paper
* Orebfuscator Version: 5.2.4
* Protocollib Version: 4.7.0

Chests and other vaults are still visible through the resource pack and through the cheat

**Comment by Ingrim4** [comment]
Can you please provide your config as a https://pastebin.com/ and provide a link to the resource pack and the name of the world your testing this on.

**Comment by Demandss** [comment]
The standard settings have not changed anything

**Comment by Ingrim4** [comment]
And what about the other two things I requested: 

> and provide a link to the resource pack and the name of the world your testing this on.

**Comment by Demandss** [comment]
tested in all worlds, and I used cheat BleachHack and texture pack Xray Ultimate

**Comment by Ingrim4** [comment]
ok but what are the world's names, the default config only works with the default world names: `world`, `world_nether`, `world_the_end` and you also considered that the default deobfuscation distance of the proximity hider is `24` blocks right?

**Comment by Demandss** [comment]
Yes

**Comment by Ingrim4** [comment]
Can you provide an example image cause for me it works perfectly fine.

**Comment by Ingrim4** [comment]
closed due to inactivity
