### ISSUE TITLE
Bugged chunks 1.18.1

### ISSUE THREAD

**Issue by QuestionCatcher** [Imprex-Development/orebfuscator#177]
* Server Version: 1.18.1 with purpur build 1491 
* Orebfuscator Version: 5.2.4 
* Protocollib Version: 4.7.0 

**Describe the bug**
When players were running around the world they often encountered "empty chunks".
The point is, some people visually saw the chunk but others didn't. Players flew  through blocks that were physically there but were not for the given player with the problem.
In this case, every chunk around them was full of ores (this plugin works)
(currently the plugin has been removed from the server over 24 hours ago and this problem does not occur)

(About screens)
This is this bugged chunk. The player who made the SS and this one with purple hoodie on skin had this problem. The others two players _Lilien and DRATHOS(in diamond set) they didn't have that problem. Chunk worked 100% for them and they were able to move freely in that area.

**The server at that time did not have any lags or TPS drops.
The players on the screenshots at that time had a good internet connection and a stable ping of 20-30ms**

Contact with me:
Discord - QuestionCatcher#1480

![chunkbug1](https://user-images.githubusercontent.com/73604198/149036477-98b4618f-264e-46c2-8f93-a775faded828.png)
![chunkbug2](https://user-images.githubusercontent.com/73604198/149036483-bea87bc9-7148-4cc8-aa03-5696d12dda2b.png)

**Comment by Ingrim4** [comment]
Currently working on a fix. Here is a temp version that should fix it: https://github.com/Imprex-Development/Orebfuscator/suites/4891314412/artifacts/140246701

**Comment by xXjojojXx** [comment]
I agree the problem is also
