### ISSUE TITLE
Seems to stop working below a certain Y level

### ISSUE THREAD

**Issue by somekoder** [Imprex-Development/orebfuscator#179]
Server Version: git-Paper-82 (MC: 1.18.1) API version 1.18.1-R0.1-SNAPSHOT
Orebfuscator Version: 5.2.4
Protocollib Version: 4.7.0

Orebfuscation seems to stop working below a certain Y level: ~ -40
![2022-01-20_23 25 15](https://user-images.githubusercontent.com/49205285/150465562-c11c0ce4-fde4-4491-93ba-2cf820b373bf.png)

![2022-01-20_23 28 39](https://user-images.githubusercontent.com/49205285/150465867-12105d56-6be0-4df2-a207-43be00a9b5c1.png)
pment/Orebfuscator/files/7910386/config.txt)

[config.txt](https://github.com/Imprex-Develo

I'm not sure how to reproduce, but I've tried clearing the cache, restarting the server and quitting and rejoining without much success.

**Comment by somekoder** [comment]
[config.txt](https://github.com/Imprex-Development/Orebfuscator/files/7910398/config.txt)
Config kinda ripped in there, here's another one

**Comment by Ingrim4** [comment]
I just tried your config and it works perfectly fine for me. (Used latest spigot, protocollib and orebfuscator version). Are your sure your method of testing isn't flawed?

**Comment by somekoder** [comment]
This is the xray resource pack I used while testing:
https://www.curseforge.com/minecraft/texture-packs/xray-ultimate-1-11-compatible

I'll try updating my version of paper and see what happens

**Comment by somekoder** [comment]
So I updated my paper version to the latest and unfortunately it seems to have the exact same behavior... I'm wondering if this is because I'm running paper? I'm also running [Terralith](https://www.curseforge.com/minecraft/mc-mods/terralith) so I'm not sure if that could be causing the issue. I'll try a few things and post back here if I discover anything

**Comment by somekoder** [comment]
I tried Paper's Anti-Xray Engine 2 and it had very similar behavior, so this problem might not be directly related to this mod... I'll close the issue for now until more information is discovered.

Thanks @Ingrim4

**Comment by KweezyCode** [comment]
![image](https://user-images.githubusercontent.com/36813920/191191356-67e784ba-e030-48b5-b2d6-d8b9d102665a.png)
i have same issue, any fix?

**Comment by NgLoader** [comment]
Please check your config that you have set the right **y** value [Wiki Config](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section)

When you upgrade from a older version of OFC the config will not automatically change the value.
