### ISSUE TITLE
Unplayable when mining (only false ores and ghostblocks)

### ISSUE THREAD

**Issue by Chevels** [Imprex-Development/orebfuscator#18]
**Please fill out the following information:**
* Server Version: 1.15.2
* Orebfuscator Version: 5.0.1
* Protocollib Version: latest devbuild (448)

**Describe the bug**
When players are mining all blocks revealed are false ore.
When players mine blocks on ground, they are stuck by virtual falling when they walk on mined place.
A member do this video to see the issues:

[2020-05-03_14-46-45.zip](https://github.com/Imprex-Development/Orebfuscator/files/4570353/2020-05-03_14-46-45.zip)
On Youtube:
https://youtu.be/JLZPbejFEG0

He must use the mod:
https://www.curseforge.com/minecraft/mc-mods/antighost
...and spam refresh key when he's mining to be able to mine correctly

I had to uninstall Ofc while waiting for the issue to be fixed because it is unplayable.

Thank you for your work !

**Comment by NgLoader** [comment]
It is not currently implemented, this version is still under development

**Comment by Chevels** [comment]
Oh sorry, I misunderstood your post on another issue...

So I'm going to wait until you give us the green light to be able to use this promising new version of Ofc :)
My encouragement anyway !
