### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by ShirefReda** [Imprex-Development/orebfuscator#182]
Im getting low fps with the plugin installed idk why 
i didnt edit anyting in the config file 
1.18.1 paper

**Comment by Ingrim4** [comment]
https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#users-experience-low-fps

**Comment by ghost** [comment]
Do I only need to change minecraft:cave_air (line 61) to 1 (or is another amount recommended?) or all blocks because the article says the weight of air but there is just one air entry?

**Comment by Ingrim4** [comment]
You should either decrease or completly remove every occurrence of air (`cave_air`, `void_air` or `air`) that is inside your config if it's an issue for you.

**Comment by ghost** [comment]
There is only one `air` entry and that's `cave_air` in line 61.

**Comment by Ingrim4** [comment]
![grafik](https://user-images.githubusercontent.com/8127996/155364192-2c04c192-5a94-4dac-9671-3be3d9ae3ec4.png)
from https://minecraft.fandom.com/wiki/Air

It's all air (`cave_air`, `void_air` or `air`) just with different names is that so hard to understand?

**Comment by ghost** [comment]
Bro is it so hard to understand there is ONLY **ONE AIR entry** no matter of what type. There is only `cave_air` and no `air` or `void_air` in the config...

**Comment by Ingrim4** [comment]
> You should either decrease or completly remove every occurrence of air (`cave_air`, `void_air` or `air`) that is inside your config if it's an issue for you.

You should either decrease or completly remove every occurrence of air (any type of air doesn't matter what type...)
