### ISSUE TITLE
orebfuscator won't work

### ISSUE THREAD

**Issue by fitydollar** [Imprex-Development/orebfuscator#184]
I am using shockbyte to host my server and you can download plugins from the website and it automatically puts them into the plugin folder. i used the latest versions to both orebfuscator (5.2.4) and protocolLib (4.7.0) and nothing happens when i use an xray pack and it shows all the ores normally. I don't even know how to use the "orebfuscator.bypass" because i dont know where to type it, i checked the console it doesnt say theres any error with the orebfuscator, i cant really know for sure if the config files have the right world name because I don't know exactly how to do it. I am also using spigot for my server so that shouldnt be the problem either. if u have a solution please give me instructions on how to get to them because i havent done things like this before and im new to it

**Comment by NgLoader** [comment]
Checkout [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues)

**Comment by 830008** [comment]
Mine isn't working either.

**Comment by 830008** [comment]
I followed everything in the wiki.

**Comment by Ingrim4** [comment]
Ok but how do you expect us to help you without a config/world names/any info at all. 😅

**Comment by Ingrim4** [comment]
closed due to inactivity
