### ISSUE TITLE
Using SlimeFun doesn't update the blocks

### ISSUE THREAD

**Issue by Dallas-Boi** [Imprex-Development/orebfuscator#190]
### Description

I am using Slimefun and there is a programable mining bot and when using it, it doesn't update the blocks so that they are back to normal. Is this a problem with the plugin or the way it was coded todo this?

### Reproduction Steps

Made a bot mine in a direction and the blocks didn't refresh

### Expected Behaviour

I thought the programable robot was able to refresh the area so the blocks would turn back into normal when a robot passed by

### Server Details

MC: 1.18.1

### Orebfuscator Version

Orebfuscator version 5.2.4

### ProtocolLib Version

ProtocolLib version 4.7.0

**Comment by NgLoader** [comment]
You need to report this issue to slimefun since they are the ones that have an integration for orebfuscator. Tell them something along the lines of the mining bot doesn't work properly with the orebfuscator integration.
