### ISSUE TITLE
Blocks like chests and hoppers on surface also is placed with random blocks

### ISSUE THREAD

**Issue by EliteAppleHacks** [Imprex-Development/orebfuscator#195]
### Description

As title says, random blocks and chests at surface level is blocked. I know theres max and minY but the values are +-2031 but minecraft is much smaller. What would it be replaced at instead?

### Reproduction Steps

Plugin enabled

### Expected Behaviour

no hiding of ores and such above y level 50 or something

### Server Details

1.16.5

### Orebfuscator Version

5.2.4

### ProtocolLib Version

na

**Comment by Ingrim4** [comment]
Just set the `maxY` to `50` (or whatever value suits your use case) in your config for all the worlds that should only obfuscate till `Y=50`. Please keep in mind that there are multiple configs (`obfuscation` and `proximity`) inside the `config.yml`. For more infomation about the config please visit our [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Config).
