### ISSUE TITLE
ping prob (lags)

### ISSUE THREAD

**Issue by Ofek270704** [Imprex-Development/orebfuscator#196]
### Description

Hello im using 1.18.1 java 17 6gb ram server, when i am with the plugin it causes very high ping and the server gets so much lags how do i fix this and the plugin causes much more high ping and lags when player dies when i disable the plugin all the probs are gone. May you help me guys to fix this?

### Reproduction Steps

server lags

### Expected Behaviour

reduce the plugin's lags and fix the engine

### Server Details

This server is running Paper version git-Paper-"bfa50ad" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: bfa50ad) You are 39 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-"c53577e" (MC: 1.17.1)

### Orebfuscator Version

5.2.4

### ProtocolLib Version

4.8.0

**Comment by legendofgow** [comment]
How you fixed ping problem?

**Comment by NgLoader** [comment]
> How you fixed ping problem?

Update to the latest version or checkout the [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#users-experience-low-fps)
