### ISSUE TITLE
Server kicks player when teleporting

### ISSUE THREAD

**Issue by enels0n** [Imprex-Development/orebfuscator#206]
### Description

Periodically, teleportations lead to a break in the connection between the player and the server.

### Reproduction Steps

Tested version: 1.12.2, 1.18.1
Just send a teleporting command like /home. But it is not always possible to cause a problem.

### Expected Behaviour

1.12.2: I have the error in console, but server doesn't kick me.
1.18.1: Error and kick.

### Server Details

git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

### Logs and Configs

Console log: https://pastebin.com/E73jRQQz
Config: https://pastebin.com/MzZwe1tc

### Extra Details

https://github.com/ViaVersion/ViaVersion/issues/2843

**Comment by Ingrim4** [comment]
Can you please tell me if this patch fixed it for you: https://github.com/Imprex-Development/Orebfuscator/suites/5686860028/artifacts/187003615

**Comment by enels0n** [comment]
https://pastebin.com/S8xS2Lcq
(When unloading chunks, new errors began to appear. https://pastebin.com/NAuwT03p )

**Comment by Ingrim4** [comment]
The new error is weird because the chunk packet supposedly uses 128 bits per block which isn't possible. Is your world tampered with in any way, like world pre-gen, custom world gen, world painter or something like that? Are you using any mods that change packets, networking or the world?

**Comment by enels0n** [comment]
[Plugin list](https://dump.viaversion.com/0a56af000635d918d3b016b9e9cc1b5ee7da41cdebe921160285da97215563e5)
Only pregeneration by WorldBorder

And I have the [same issue](https://github.com/Imprex-Development/Orebfuscator/issues/207)
