### ISSUE TITLE
Blocks like furnaces, chests and crafting tables are rendered as wrong block after joining

### ISSUE THREAD

**Issue by dotI0** [Imprex-Development/orebfuscator#207]
### Description

After joining a server, blocks as furnaces, chests etc. are rendered as a wrong block as long as you don't click it.

### Reproduction Steps

Install plugin on Paper 1.18.2 and join a server with visible furnaces and chest at your location

### Expected Behaviour

Blocks should be rendered as right block if visible at join position

### Server Details

Paper version git-Paper-242 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: aab1f8a)

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

### Logs and Configs

https://gist.github.com/dotI0/64b3b076caf22ad3666bc67eef825541

### Extra Details

How it looks after joining the server:
![2022-03-14_23 40 41](https://user-images.githubusercontent.com/54602589/158273293-5a3b16b1-9e1a-4b89-b7c2-043562917636.png)

How it looks after clicking one of the blocks:
![2022-03-14_23 40 45](https://user-images.githubusercontent.com/54602589/158273360-bfd6c0c3-661a-4f48-8cb2-f8e9310e73fb.png)
![2022-03-14_23 40 49](https://user-images.githubusercontent.com/54602589/158273378-ba17218b-4ce1-45e0-8b6f-0e0a24a9df55.png)

How it should look:
![2022-03-14_23 40 54](https://user-images.githubusercontent.com/54602589/158273404-cb7ec67b-4ba4-4a54-9579-0a8dc292ec5a.png)

**Comment by Ingrim4** [comment]
Can you please tell me if this patch fixed it for you: https://github.com/Imprex-Development/Orebfuscator/suites/5686860028/artifacts/187003615

**Comment by dotI0** [comment]
Unfortunately not.. :(

![2022-03-17_11 58 36](https://user-images.githubusercontent.com/54602589/158795111-50f39a4b-a946-4ad2-88f4-1cf81c43d59a.png)

**Comment by dotI0** [comment]
Unfortunately, the blocks are now always rendered incorrectly. Not like before, where the blocks were correct again when the chunk was reloaded. When I click a block, it becomes normal. If I then walk away (or change dimensions, or log out) and come back, the blocks are rendered incorrectly again.

**Comment by Ingrim4** [comment]
That's weird, the patch waits till the player successfully received the chunk and then checks if an proximity hidden blocks can be deobfuscated. It works for so idk what's the problem. Do you have any other plugins installed that could mess with packets and their send order?

**Comment by dotI0** [comment]
These are my Plugins:
![image](https://user-images.githubusercontent.com/54602589/158816368-a40aabc9-43c3-4817-9f64-78e82eb9758b.png)

**Comment by Ingrim4** [comment]
You could try setting `advanced.useAsyncPacketListener` ([useAsyncPacketListener](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#advanced)) to `false` that might do the trick.

**Comment by NgLoader** [comment]
> These are my Plugins: ![image](https://user-images.githubusercontent.com/54602589/158816368-a40aabc9-43c3-4817-9f64-78e82eb9758b.png)


Did you really tested the latest version?
Normally your file name shoud be ``orebfuscator-plugin-5.2.6-b131.jar`` and not ``orebfuscator-plugin-5.2.6.jar`` when your using Ingrim4's patch.

[Download Patch](https://github.com/Imprex-Development/Orebfuscator/suites/5686860028/artifacts/187003615)

**Comment by dotI0** [comment]
I replaced Ingrim4's patch with the original file after testing, because the patch makes the problem much worse than it is.
(Seen in my comment after testing the patch)

I will test the option advanced.useAsyncPacketListener and let you know if it works.

**Comment by dotI0** [comment]
> You could try setting `advanced.useAsyncPacketListener` ([useAsyncPacketListener](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#advanced)) to `false` that might do the trick.

Now the blocks are completely invisible when joining with them in the visible area.
But the blocks will become visible if the player moves slightly.
I think that should work for me and the players on the server.

If not, I will tell you.
Thank you very much for your help!!

On Join:
![2022-03-18_23 54 33](https://user-images.githubusercontent.com/54602589/159094767-61fd7a2c-c4ab-4cb1-99d4-e081a06072df.png)

After moving slightly:
![2022-03-18_23 54 36](https://user-images.githubusercontent.com/54602589/159094791-7a0cec47-ad9a-4cbe-9d02-88650471f2d8.png)
