### ISSUE TITLE
After installation nothing works

### ISSUE THREAD

**Issue by shinefield** [Imprex-Development/orebfuscator#208]
### Description

After installation nothing works

### Reproduction Steps

Copy and paste to start the server

### Expected Behaviour

Perspective should not see minerals

### Server Details

catserver1.12

### Orebfuscator Version

orebfuscator-plugin-5.2.6

### ProtocolLib Version

ProtocolLib4.8.0

### Logs and Configs

no error log, default config

**Comment by Ingrim4** [comment]
Can you maybe specify what's not working because "nothing works" isn't particularly helpful?

**Comment by shinefield** [comment]
@Ingrim4 Minerals have no camouflage

**Comment by NgLoader** [comment]
Checkout [Wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated)
