### ISSUE TITLE
1.18.2 Orebfuscator Not Working Using X-Ray Ultimate Pack

### ISSUE THREAD

**Issue by Daniel3614** [Imprex-Development/orebfuscator#209]
### Description

I downloaded and installed the latest version of both plugins twice. There was no errors in the console when the server loaded. Yet the plugin does not work when using an X-Ray Ultimate resource pack.

### Reproduction Steps

1. Download both plugins.
2. Insert both .jar in the Plugins folder.
3. Start server.
4. Join world.
5. Use latest version of X-Ray Ultimate resource pack for 1.18.2

### Expected Behaviour

The plugin should work when using the resource pack.

### Server Details

3470-Spigot-ffceeae-1092219 (MC: 1.18.2)

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

**Comment by NgLoader** [comment]
Checkout [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated)
