### ISSUE TITLE
Endless loading of the world while the plugin is running

### ISSUE THREAD

**Issue by d3adwolf** [Imprex-Development/orebfuscator#212]
### Description

I have a proxy server Waterfall and under it three Purpur servers, I updated ProtocolLib to the current and working build, updated your plugin from 5.2.5 to 5.2.6 and when you enter the server with this plugin (Purpur 1.18.2) and me endless loading world, plus the server writes that the overload.

### Reproduction Steps

Go to the server with the plugin > download world > ♾

### Expected Behaviour

Go to the server with the plugin > world load > calm gameplay

### Server Details

Purpur 1.18.2

### Orebfuscator Version

5.2.5 & 5.2.6

### ProtocolLib Version

5.0.0-SNAPSHOT-b553

**Comment by KioProject123** [comment]
I'm not sure whether it's ProtocolLib or Orebfuscator or Purpur problem.
The latest release version instead of the build version of ProtocolLib does not have this problem.
So I guess this is the problem caused by ProtocolLib

**Comment by d3adwolf** [comment]
All fixed, the problem was ProtocolLib, so you were totally right, thanks. There was a build under version 5.0.0, I downloaded the stable 4.8.0 and everything worked fine, why I did not notice the stable version before - I do not understand. In any case, thanks for the help!
