### ISSUE TITLE
Config gets reset every time I apply changes

### ISSUE THREAD

**Issue by ghost** [Imprex-Development/orebfuscator#213]
### Description

I edit the files so the weight of stone is higher than all the others, I reload/restart server to apply changes (after applying changes to the file of course.), and then the weight of stone gets changed back to one.

### Reproduction Steps

Edit config.yml
Change any weight value
Restart/reload server
All values set to default.

### Expected Behaviour

Edit config.yml
Change weight value
Restart/reload server
All values are changed to intended values.

### Server Details

Paper version git-Paper-792 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Orebfuscator Version

5.1.2

### ProtocolLib Version

4.8.0

### Logs and Configs

[WARNING] .... [bukkit.orebfuscator] [Orebfuscator] config path 'cache.baseDirectory' is no child directory of '/home/gs-40713'
[INFO] .... [bukkit.orebfuscator] [Orebfuscator] cache.protocolLibThreads is less than one, choosing processor count as value = 3
[INFO] .... [bukkit.orebfuscator] [Orebfuscator] Searching NMS protocol for server version "v1_16_R3"!
[INFO] .... [bukkit.orebfuscator] [Orebfuscator] NMS protocol for server version "v1_16_R3" found!

### Extra Details

Server Provider: Server.pro

**Comment by NgLoader** [comment]
Your using an older version, in this version from ofc is storing the files on load and unload.

Please use the lastest release version
