### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Wispect** [Imprex-Development/orebfuscator#215]
### Description

I already followed these steps

Check that the player doesn't have the orebfuscator.bypass permission
Check if you have installed the latest version of [Orebfuscator](https://github.com/Imprex-Development/Orebfuscator/releases) and [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/) for your game version
Check if there are any warnings in the console about a wrongly configured config
Check if you used the correct world names in the config

and none brings the solution

### Reproduction Steps

it just doesn't work

### Expected Behaviour

let it work normally

### Server Details

forge-1.16.5-36.2.33-534a162-DEV

### Orebfuscator Version

5.2.6

### ProtocolLib Version

ProtocolLib v4.8.0 

### Extra Details

I already installed everything and tried different versions of the plugin and none works, the server is magma a server that works with spigot/bukkit plugins and mods

**Comment by NgLoader** [comment]
Maybe you forgot to change the world name?

**Comment by NgLoader** [comment]
The problem may be due to magma, I will test that tomorrow

**Comment by Wispect** [comment]
I tried it and it "worked" only it doesn't load the world

**Comment by NgLoader** [comment]
Maybe, it is because of magma.
Please read the comment from Ingrim4 in https://github.com/Imprex-Development/Orebfuscator/issues/191#issuecomment-1036672745

**Comment by Ingrim4** [comment]
closed due to inactivity
