### ISSUE TITLE
Removed plugin

### ISSUE THREAD

**Issue by NotNoison** [Imprex-Development/orebfuscator#217]
### Description

Hey I removed the plugin and everytime I break block in creative it's a visual of the ores and it's just really annoying.

### Reproduction Steps

Break a natural stone in the world after removing the plugin.

### Expected Behaviour

Nothing when breaking a stone or netherrack 

### Server Details

Pufferfish 1.18

### Orebfuscator Version

4.4.3

### ProtocolLib Version

4.80

### Logs and Configs

None - As I've removed the plugin

**Comment by NotNoison** [comment]
![Ij3fLvt9UX](https://user-images.githubusercontent.com/86527549/167825740-ea07f24b-fd99-4250-a9af-24e7e11058f0.gif)

**Comment by Ingrim4** [comment]
Looks to me like you didn't remove Orebfuscator from your server unless your server has some kind of packet cache which I highly doubt. To be 100% sure you removed Orebfuscator you could execute `/protocol dump` on your server and provide the content of the dump file to us or check yourself if there are still Orebfuscator listeners in which case you didn't remove Orebfuscator.

**Comment by NotNoison** [comment]
> 

It seems like it's something in my paper.yml

**Comment by NotNoison** [comment]
https://pastebin.com/Qj8wveda When I replace my paper.yml it is fixed but when I use my optimized one it doesn't work
..

**Comment by NotNoison** [comment]
https://pastebin.com/i1RJ3jBc -> This is my optimized paper

**Comment by Ingrim4** [comment]
You enabled paper's built-in anti-xray in line 274 of your paper.yml. This has nothing to do with Orebfuscator.

**Comment by NotNoison** [comment]
> You enabled paper's built-in anti-xray in line 274 of your paper.yml. This has nothing to do with Orebfuscator.

Omg I'm retarded I looked at it for so long trying to figure out what's wrong.

**Comment by NgLoader** [comment]
So, the problem is fixed?

**Comment by NotNoison** [comment]
Yes sorry for the delays lol you can close this.
