### ISSUE TITLE
I see anything, I see just the sun and the cloud

### ISSUE THREAD

**Issue by 91leMAC** [Imprex-Development/orebfuscator#218]
### Description

I have instal this plugin, every work. But the generation are very very slow.
When I disconnect and I reconnect, I can't see anything. I can't moove, place a block.

For resolving I run /reload and then I see normally all blocks I can break and place a block.
But world edit plugin will not work and after a fiew second of lagging/freezing I got disconnected 
the error : 
time out

### Reproduction Steps

Maybe setup a mohist server ? (but I don't now if Mohist have trouble with this plugin).

### Expected Behaviour

Normally I must see all blocks, but now I don't see anything, and it's not only me. My friends have also the same problem.

### Server Details

Mohist 1.16.5

### Orebfuscator Version

5.2.6

### ProtocolLib Version

ProtocolLib.jar (he has no numbers after his name)

### Logs and Configs

**Logs :
https://mclogs.minestrator.com/2p33q7L**

Config :
https://www.toptal.com/developers/hastebin/imuxuruvad.less

### Extra Details

If you have no solutions you can give me other xrays that work the same.

**Comment by NgLoader** [comment]
Checkout our wiki [Some/all chunks aren't sent/rendered (world appears empty)](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#someall-chunks-arent-sentrendered-world-appears-empty)

**Comment by Ingrim4** [comment]
closed due to inactivity
