### ISSUE TITLE
Engine mode 1 does not work and breaks config file

### ISSUE THREAD

**Issue by Jtcoop** [Imprex-Development/orebfuscator#219]
### Description

When changing the engine mode from "version: 2" to "version: 1" the plugin stops working altogether and makes the config file significantly smaller, deleting all of the blocks that are hidden and replaced for each dimension. The config needs to be deleted and regenerated to fix it. I am very confused by this. The plugin works well but I preferred engine mode 1 in previous versions. Is it still possible to use this?

### Reproduction Steps

Change version at the top of the config to 1, start the server. Check the config.

### Expected Behaviour

Plugin switches to engine mode 1 and still mostly prevents xray and esp, does not change config by itself.

### Server Details

Paper version git-Paper-349 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: b6a6544) 

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

**Comment by Ingrim4** [comment]
I don't know what you're referring to as engine mode 1 but the field that you changed is the config version which our documentations explicitly tells you not to change unless you have good reason to do so: https://github.com/Imprex-Development/Orebfuscator/wiki/Config

**Comment by NgLoader** [comment]
Checkout #113
