### ISSUE TITLE
update 1.19

### ISSUE THREAD

**Issue by FielSteve** [Imprex-Development/orebfuscator#220]
### Description

i want the plugin to be supported to 1.19, looking forward to it.

### Proposed Behaviour

I currently have a 1.19 server but I don't dare to open it for fear of being xray player, this will lose the quality of the game

### Extra Details
plugin is very good after my FPS settings as well as others have not dropped, I hope the plugin will go to 1.19

**Comment by NgLoader** [comment]
This Plugin will be updated to 1.19 soon

**Comment by FielSteve** [comment]
thank you, I really support that plugin :))
