### ISSUE TITLE
Remove Protocolib

### ISSUE THREAD

**Issue by DOSEV5** [Imprex-Development/orebfuscator#222]
### Description

Hello mr developer. Why this plugin need protocolib. 
You updated this plugin for 1.19 really fast... that is good. But now i need to wait for protocolib 1.19 and i dont know when this will happen. Protocolib developer activity is realy low, so i think it wont be soon. Sooo. Why dont you make the plugin without protocolib ,because now it is specifically slowing down the update process for many servers.

### Proposed Behaviour

Idk anything about coding. Only know protocolib is need for opimization

**Comment by Ingrim4** [comment]
No we need ProtocolLib! Just use their dev versions: https://ci.dmulloy2.net/job/ProtocolLib/
