### ISSUE TITLE
How do I use the OFC permissions

### ISSUE THREAD

**Issue by JustSomeDude69** [Imprex-Development/orebfuscator#223]
### Description

How do i give myself the perms for stuff like orebfuscator.bypass how do i do that? do i write it in the chat or what? sorry for being dumb

### Reproduction Steps

idk

### Expected Behaviour

i expected it to be a command

### Server Details

PaperMc 1.18.2

### Orebfuscator Version

5.3.0

### ProtocolLib Version

4.8.0

**Comment by NgLoader** [comment]
Checkout [Permission issue](https://github.com/Imprex-Development/Orebfuscator/issues/193#issuecomment-1036475793)

Or you can just use a permission system plugin like LuckPerms, PermissionX or something else. 😃
