### ISSUE TITLE
weird Chat message

### ISSUE THREAD

**Issue by FinnDetlev** [Imprex-Development/orebfuscator#224]
### Description

Idk why but Orebfuscator is posting a message every few seconds into the chat 

### Reproduction Steps

![image](https://user-images.githubusercontent.com/67942455/173407856-c25b50c8-99cb-4091-aee1-77e188c0949d.png)

### Expected Behaviour

lol

### Server Details

PAPER 1.19 Build #10

### Orebfuscator Version

5.3.0

### ProtocolLib Version

4.8.0

**Comment by FinnDetlev** [comment]
i think it isn't problem with Orebfuscator its ProtocolLib

**Comment by NgLoader** [comment]
Please use the latest ProtocolLib [build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

**Comment by Nicholindo** [comment]
Yes, but can you add more to explaining why does this issue happen because both me and @GrasshopperGit  have the latest build of ProtocolLib, and it seems it is the one causing the issue here. Also is there a way to fix the problem?

**Comment by NgLoader** [comment]
> Yes, but can you add more to explaining why does this issue happen because both me and @GrasshopperGit have the latest build of ProtocolLib, and it seems it is the one causing the issue here. Also is there a way to fix the problem?

Yea, ur using the latest version for 1.18 not for 1.19 which has internal changes in ProtocolLib which occurred the chat message.
Download the latest protocollib version from jenkins, not from spigot! ``the spigot version is for 1.18``
You can find the latest jenkins build [here](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

You can also see that on the spigot page from Protocollib that he says:
> Use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for Minecraft 1.19
Use the [latest release](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0) for all other recent Minecraft versions

![image](https://user-images.githubusercontent.com/13753840/187759970-1459ad15-8fe5-4d7d-8bab-0a38f8a3195b.png)

**Comment by Nicholindo** [comment]
It did fix the problem thank you very much gentleman.
