### ISSUE TITLE
Loading Terrain When Joining Dedicated Server

### ISSUE THREAD

**Issue by Skapes7** [Imprex-Development/orebfuscator#226]
### Description

Im having an issue where whenever players try to join the server (Only Orebfuscator and ProtocolLib installed) the client gets stuck on "Loading Terrain". The server still registers the player joining, and audio can be heard through the client (NPC's moving etc.). Occasionally this error doesn't occur and the player can join the server, but relogging or changing dimensions causes the issue to arise again. With further testing, the issue seems to arise only after changing the world spawn and creating a world border.

### Reproduction Steps

1. Install Orebfuscator and ProtocolLib
2. Change world spawn and create world border
3. Change Dimensions/Relog/Reload Terrain

### Expected Behaviour

Player should be able to reload terrain without getting stuck on the "Loading Terrain" screen

### Server Details

3544-Spigot-475f600-991aeda (MC: 1.19)

### Orebfuscator Version

5.3.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b573

### Extra Details

- I've tried versions of ProtocolLib released since June 8th (first 1.19 dev build) up to latest build (Listed above)
- Havent encountered this issue in the past (Only arose in 1.19)
- No console errors

**Comment by Ingrim4** [comment]
Have you tried if [`advanced.useAsyncPacketListener`](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#advanced) set to `false` is fixing the issue for you?

**Comment by Skapes7** [comment]
Yup that seems to have worked - that was a simple fix
Thanks!
