### ISSUE TITLE
Multiverse-Core 

### ISSUE THREAD

**Issue by FielSteve** [Imprex-Development/orebfuscator#227]
### Description

Hi, I have created 2nd overworld on server using Multiverse-Core plugin and named it world2, but anti xray doesn't run on world2, so I want a way to make Orebfuscator plugin run on world2?

### Proposed Behaviour

is there any way to add world2 in config?

### Extra Details

.

**Comment by NgLoader** [comment]
Checkout [wiki](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section)
