### ISSUE TITLE
Bug with hidden ores

### ISSUE THREAD

**Issue by DimaSergeew** [Imprex-Development/orebfuscator#228]
### Description

there is a bug that are not hiding happy below minus coordinates

### Reproduction Steps

using cheats with Xray enabled, go below 0, on game version 1.19

### Expected Behaviour

Ores must be hidden completely

### Server Details

Mirai 1.19

### Orebfuscator Version

5.3.0

### ProtocolLib Version

Assembly #575 (07.07.2022 7:53:38)

**Comment by NgLoader** [comment]
Please first checkout this sites:
- [Common Issues - I Don't see any blocks obfuscated](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated)
- [Config - Obfuscation config section](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section)

Or your using an old version, try to rename the current config file and check if the new config works.
