### ISSUE TITLE
Chunks disappear in 1.19

### ISSUE THREAD

**Issue by DimaSergeew** [Imprex-Development/orebfuscator#229]
### Description

My friend and I have the orebfuscator plugin on the servers, and it happens that at the same time all the chunks on the server disappear and the players cannot move. We thought the problem was in the kernel, but the kernel developer, having studied everything about our server, said to apply here, indicating that the reason is in the orebfuscator, it happens that over time, chunks simply disappear abruptly for everyone and they simply cannot move

### Reproduction Steps

It's hard to say how to repeat this, it happens after a random time and only restarting the server helps

### Expected Behaviour

-
![unknown](https://user-images.githubusercontent.com/75163645/179419493-02edcc10-bad5-41ff-9fb9-439aacde923b.png)

### Server Details

This server is running Mirai version git-Mirai-62bf4cb (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 62bf4cb on ver/1.19)

### Orebfuscator Version

Orebfuscator (Anti X-Ray) 5.3.0

### ProtocolLib Version

Build #575 (07/07/2022 07:53:38)

**Comment by Ingrim4** [comment]
The exception you're getting looks strange, it would involve the a thread loosing the lock which should be impossible in any scenario that I can think of. What Java version do you use and could you try updating it? Cloud you send me the output of this command (executed on your dedicated machine (Windows/Linux/MacOS)): `java --version`?

Should look something like this:
```
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```

**Comment by DimaSergeew** [comment]
> java --version

![Screenshot_1](https://user-images.githubusercontent.com/75163645/179976454-4b2dc139-5dc5-4812-a7b6-a621efd245f2.png)

**Comment by Ingrim4** [comment]
Temurin should be fine so I can't really tell how to fix this. There is however the option of simply disabling the cache inside the config ([`cache.enabled`](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#cache)) which should only slightly degrade performance.

I could also add an option to only disable the file cache and keep the memory cache enabled which would also mitigate the issue your facing but not degrade the performance too much. If that is something you need simply open a new issue where request this feature.
