### ISSUE TITLE
Orebfuscator gives errors while starting.

### ISSUE THREAD

**Issue by jinglebryce** [Imprex-Development/orebfuscator#230]
### Description

Orebfuscator gives this error while starting, then gives another error while trying to disable itself.

I have attempted a few things such as disabling the cache, downgrading orebfuscator, removing some recently updated plugins, all to no avail.

### Reproduction Steps

I... have no idea. This started happening randomly after I took a week-long break from my server. 

### Expected Behaviour

Orebfuscator should be able to enable and disable properly.

### Server Details

git-Paper-387 (MC: 1.18.2)

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

### Logs and Configs

https://pastebin.com/iGBB78MA

**Comment by NgLoader** [comment]
Please try to rename your currently orebfuscatior config to something else and let it be regenerated.
Its seems that you have modified your config and deleted the wrong values.

**Comment by Ingrim4** [comment]
Also consider updating to the [latest version](https://github.com/Imprex-Development/Orebfuscator/releases/latest).
