### ISSUE TITLE
Option "deleteRegionFilesAfterAccess" not working 

### ISSUE THREAD

**Issue by VaclavKlima** [Imprex-Development/orebfuscator#231]
### Description

Today I looked at the cache folder and it had 36Gb of data which means that the plugin is not deleting old data...
I looked in the config and I had the default value for the "deleteRegionFilesAfterAccess" (2 days).
Then I looked in the folder and found files that were updated a month ago and so on...

### Reproduction Steps

Cache some chunks and then don't load them for more than the set value "deleteRegionFilesAfterAccess" 

### Expected Behaviour

The old cache should be deleted after expiry duration

### Server Details

git-Purpu-1610 mc ver: 1.18.2

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

### Logs and Configs
[config.txt](https://github.com/Imprex-Development/Orebfuscator/files/9151798/config.txt)

### Extra Details

I'm reporting this bug because the backup of the server was 2x bigger than it should...

For now, I just moved the "baseDirectory" to another folder so I don't have to backup server with the cache

**Comment by Ingrim4** [comment]
I haven't done any testing yet but cache files only get deleted if the file's `lastAccessTime` is older then the configured value. So are you sure the files haven't been accessed in the last 2 days?
