### ISSUE TITLE
high ram

### ISSUE THREAD

**Issue by mrlota29** [Imprex-Development/orebfuscator#233]
### Description

There is a high ram on the server, when I remove the plugin the ram is dropping. I noticed that when I delete the orebfuscator_cache file, the ram drops for a few hours.

### Reproduction Steps

idk

### Expected Behaviour

.

### Server Details

purpur 1.18.2

### Orebfuscator Version

5.3.0

### ProtocolLib Version

protocolib 4.8.0

### Logs and Configs

https://timings.aikar.co/dev/?id=3f3fbc2207a941eaa4dd284e5bd1ed1b

**Comment by Ingrim4** [comment]
What exactly does `high ram` mean and how did you measure that?

**Comment by mrlota29** [comment]
I don't know what happened, plugin stopped working today. Is red. Nothing was done with it

**Comment by mrlota29** [comment]
as I remove the plugin, the ram falls off

**Comment by NgLoader** [comment]
> I don't know what happened, plugin stopped working today. Is red. Nothing was done with it

Can you please provide some more info?
Like log files?

**Comment by Ingrim4** [comment]
Closed due to inactivity.
