### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by lexteer** [Imprex-Development/orebfuscator#235]
### Description

I installed The Orebfuscator and downloaded ProtocolLib. I also disabled my bypass. That I tried putting on Xray and nothing happens. I see all ores as I would normaly.

### Reproduction Steps

Install Orebfuscator,
Install ProtocolLib,
Disable orebfuscator.bypass with luck perms,
put on Xray.

### Expected Behaviour

To work! Stone should be viewed as different ores.

### Server Details

paper 1.19.2

### Orebfuscator Version

5.3.0

### ProtocolLib Version

Latest Dev build, Aug 17

**Comment by Ingrim4** [comment]
Make sure you follow this guide: https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated

If that didn't help please provider your config and world name.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
