### ISSUE TITLE
Holes in obfuscated chunks

### ISSUE THREAD

**Issue by Bobcat00** [Imprex-Development/orebfuscator#241]
### Description

If I use an xray texture pack, there are various "holes" in obfuscated parts below ground, where I can see into the void. As I move around, the holes also move around, and some chunks that show the ores will disappear again.

Note this is in the overworld.

To be clear, the plugin is still effective, but why are these holes there and why do they change?

![2022-09-12_15 14 46](https://user-images.githubusercontent.com/3617206/189737859-8598fd31-e6da-4b02-81cd-d6941d96ee9d.png)

### Reproduction Steps

Using Optifine and the Xray Ultimate resource pack, fly above the ground and observe the below ground chunks.

1.19.2-Optifine_HD_U-H9
Xray_Ultimate_1.19_v4.2.3.zip - https://www.curseforge.com/minecraft/texture-packs/xray-ultimate-1-11-compatible

### Expected Behaviour

The underground areas should be covered with ores, without holes to the void.

### Server Details

Paper version git-Paper-142 (MC: 1.19.2)

### Orebfuscator Version

5.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b598

### Logs and Configs

https://pastebin.com/2psWBJVe

**Comment by Ingrim4** [comment]
That sound like a client-side render issue nothing to be worried about. If the blank spots move along as you move and the chunks were obfuscated before they will stay obfuscated no matter what you do. I would guess the client can't deal with the complex geometry and just starts producing non sense xD.

**Comment by Ingrim4** [comment]
Maybe reducing the amount of obfuscation materials would solve this odd behavior.
