### ISSUE TITLE
Error "An error occurred while obfuscating chunk..."

### ISSUE THREAD

**Issue by Chevels** [Imprex-Development/orebfuscator#244]
### Description

Hello :)
For a few days when a member of the server is at its base, I have this error messages which spams my console : see **Logs and config section**

I specify that there was no modification of config, nor of update before this problem appears. It appeared for no apparent reason.

### Reproduction Steps

Get close to the chunks reported in the error messages. As soon as this area is loaded, these errors spams my console.

### Expected Behaviour

That I can find a readable console and lighter logs !^^

### Server Details

Paper version git-Paper-138 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 09904fd)

### Orebfuscator Version

5.3.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### Logs and Configs

[https://pastebin.com/4kLQ2ZDy](https://pastebin.com/4kLQ2ZDy)

**Comment by Ingrim4** [comment]
Could you please provide the region file of the affected chunk (`r.-4.-5.mca` of world `Heavy`)? This would help enormously with debugging. Additionally it would help if you could provide the contents of a protocollib dump (execute `/protocol dump` on your server).

**Comment by Chevels** [comment]
Hello,
Sorry, I didn't answer because I was waiting for it to happen again so I could do the /protocol dump command at the time of the bug.
The problem is that it did it for 2-3 days, then it doesn't do it anymore...
Do you want me to give the region file anyway or I wait first to see if the bug reoccurs ?

**Comment by Ingrim4** [comment]
Nah just send me the region file and you can execute the `/protocol dump` command anytime. The content of the command is important no matter if the bug occurred or it didn't.

**Comment by Chevels** [comment]
Here is the region file and protocollib dump.
Sorry for the delay, I was very busy this month
[Region file & dump protocollib.zip](https://github.com/Imprex-Development/Orebfuscator/files/10054114/Region.file.dump.protocollib.zip)

**Comment by Ingrim4** [comment]
The region file and chunks look good to me but there is another plugin called `RealisticSeasons` on your server which is listening to chunk packets before Orebufscator which could cause some problems in cause `RealisticSeasons` wrongly formats/modifies the chunk packets. If the problem should persists you could try to disable `RealisticSeasons` and check it that fixed the issue otherwise try contacting the Devs of `RealisticSeasons` about the problem and see what they have to say regarding it.

**Comment by Chevels** [comment]
OK. This bug only occurs in one place on my map and has never happened anywhere else. I think I'll leave it like that.
What surprises me is that I have been using RealisticSeasons for several months and that this bug has never occurred except in this specific area. And the 2 plugins work very well.

Occasionally I'll talk to the developer of RealisticSeason so he knows his plugin is incorrectly modifying the chunk packets.

Thanks for watching all of this !

**Comment by PystoyPlayer** [comment]
hey. Can you check my errors too pls ?

https://pb.superhub.xyz/rwrkZa?fmt=raw
https://pb.superhub.xyz/TW8GDd?fmt=raw

**Comment by Ingrim4** [comment]
> hey. Can you check my errors too pls ?
> 
> https://pb.superhub.xyz/rwrkZa?fmt=raw https://pb.superhub.xyz/TW8GDd?fmt=raw

If your errors still persist then please open a new issue for them
