### ISSUE TITLE
adding to another dimension 

### ISSUE THREAD

**Issue by BRBKING** [Imprex-Development/orebfuscator#245]
### Description

adding the pluing to the a resource world how would i got about that 

### Reproduction Steps

none

### Expected Behaviour

none

### Server Details

This server is running Paper version git-Paper-"09904fd" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 09904fd) You are 96 version(s) behind Download the new version at: https://papermc.io/downloads

### Orebfuscator Version

5.31

### ProtocolLib Version

5.0.0

**Comment by Ingrim4** [comment]
https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section

**Comment by Ingrim4** [comment]
Closed due to inactivity.
