### ISSUE TITLE
ores everywhere

### ISSUE THREAD

**Issue by Jmitch700** [Imprex-Development/orebfuscator#247]
### Description

do you know how I make all the stone and deepslate look like ores? 

### Reproduction Steps

do you know how I make all the stone and deepslate look like ores? so um

### Expected Behaviour

do you know how I make all the stone and deepslate look like ores?

### Server Details

spigot 1.19.2

### Orebfuscator Version

5.3.1

### ProtocolLib Version

4.7.1 snapshot

**Comment by Jmitch700** [comment]
not bug didnt know how to ask for help

**Comment by NgLoader** [comment]
Checkout #113

**Comment by Jmitch700** [comment]
> 

i look at that and did it but still didnt work

**Comment by NgLoader** [comment]
> > 
> 
> i look at that and did it but still didnt work

Please check out our wiki [obfuscation config section](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section)

You just need to add stone and deepslate to hidden ores and remove them from random ores.
Please check that your editig the right world!
