### ISSUE TITLE
add cobwebs / mines to default config

### ISSUE THREAD

**Issue by Tizooo** [Imprex-Development/orebfuscator#249]
### Description

would be cool if the default config hides cobwebs / mines since its easy to find loot/ spawners with xray if filtering for this

### Proposed Behaviour

ye add cobwebs and all that stuff thats in a mine (see image)

### Extra Details

![image](https://user-images.githubusercontent.com/34001316/204934345-93416d1d-8aac-4604-a46c-da849396b619.png)

**Comment by Ingrim4** [comment]
We will not add commonly in mines occurring blocks to the default config because people use oak wood (planks/fences) in their builds which would cause them to get hidden as well and would I our opinion hinder the user experience too much.
