### ISSUE TITLE
Support for 1.19.3

### ISSUE THREAD

**Issue by Ingrim4** [Imprex-Development/orebfuscator#251]

**Comment by Bobcat00** [comment]
Can you do a release for this? Or is there a dev build server?

**Comment by NgLoader** [comment]
> Can you do a release for this? Or is there a dev build server?

yes, you can download the currently dev build's from github actions
Just select wich build you want and then under **Artifacts** you can finde a **orebufscation-plugin** file.
[1.19.3 Dev build](https://github.com/Imprex-Development/Orebfuscator/actions/runs/3662634606)

Please note that this a currently a dev build and can produce some errors
