### ISSUE TITLE
Client can highlight real ores

### ISSUE THREAD

**Issue by lukasbaxter** [Imprex-Development/orebfuscator#256]
### Description

my friend made his own client script that highlighted the real ores. the fake ores do show up, but the real ores are different then the fake for him

### Reproduction Steps

im not sure

### Expected Behaviour

to hide real ores

### Server Details

paper 1.19.2 #345

### Orebfuscator Version

5.3.2

### ProtocolLib Version

5.0.0-snap-b607

**Comment by Ingrim4** [comment]
Can't help you without the config, logs and his script.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
