### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by booblicker129** [Imprex-Development/Orebfuscator#257]
### Description

I'm using an apex server host and I have protocol and orebfuscator installed in the plugin directory. When I join the server and test if it works it does not seem to be working. When using /plugin it says I have both of the necessary things installed.

### Reproduction Steps

Start a spigot 1.19.3 server with Orebfuscator (Anti X-Ray) and ProtocolLib (Build #608) installed.

### Expected Behaviour

Plugin runs as expected.

### Server Details

3611-Spigot-61bffe0-19e6be0 (MC: 1.19.3)

### Orebfuscator Version

5.3.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b608

**Comment by Ingrim4** [comment]
Have you already tried this: https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#i-dont-see-any-blocks-obfuscated
