### ISSUE TITLE
Orebfuscator breaks recipes

### ISSUE THREAD

**Issue by Roetchi** [Imprex-Development/orebfuscator#259]
### Description

when I download Orebfuscator to my server suddenly all of the crafting recipes disappear no one can craft I don't know how this happens but I don't understand how this could happen I

### Reproduction Steps

I have purpur downloaded on my server a fork of spigot I don't know how can you reproduce it but I can send my logs

### Expected Behaviour

it should not delete recipes but it does

### Server Details

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) Error obtaining version information

### Orebfuscator Version

5.3.2

### ProtocolLib Version

4.8.0

### Logs and Configs

https://gist.github.com/Roetchi/b27b95252bf570b55ab1b6c55af0ff37

### Extra Details

i dont have any more details this only happens when Orebfuscator is instaled.

**Comment by NgLoader** [comment]
Orebfuscator only modifies the chunk packets and nothing else.

You can try to download the latest ProtocolLib version and check if it was a bug there.

Your log is also saying that some recipes are removed from the player, that can happen when a recipe was registered from a plugin and the plugin was removed or has not registered it again or it was removed from a other plugin but nothing todo with OFC.

**Comment by Ingrim4** [comment]
> Orebfuscator only modifies the chunk packets and nothing else.

Can 100% confirm this is true. You could try to see if the same thing happens on a clean server install if it doesn't it's not our fault. I would guess some other plugin doesn't like Orebfuscator and has a problem with it. You could provide a ProtocolLib dump (`/protocol dump`) and I will see what I can do but I honestly don't expect this to be fixable on our end.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
