### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by notikj** [Imprex-Development/orebfuscator#262]
### Description

Hello, there is a server crash. In the description he writes about Orebfuscator. https://pastes.dev/jez0hfzARG

### Reproduction Steps

It is unclear why this is happening

### Expected Behaviour

Crash correction

### Server Details

Dionysus 1.12.2

### Orebfuscator Version

5.3.0

### ProtocolLib Version

v5.0.0-SNAPSHOT-b577

**Comment by Ingrim4** [comment]
Please update Orebfuscator to the latest version and check if the problem still persists.
