### ISSUE TITLE
The commands doesnt work

### ISSUE THREAD

**Issue by HammadAkhtar2** [Imprex-Development/orebfuscator#266]
### Description

I try to use the Orebfuscator commands but they dont show up and when I try to use them it just denies that there are commands like that. Like when I use orebfuscator.bypass it says: "Unkown Command".

### Reproduction Steps

Open a 1.16.5 server install spigot and download the specified orebfuscator and protocollib

### Expected Behaviour

I expected that the commands would show up and work

### Server Details

Spigot (MC: 1.16.5)

### Orebfuscator Version

5.2.4

### ProtocolLib Version

4.5.1

**Comment by Ingrim4** [comment]
That's not a command it's a permission. You need a separate permission plugin to change a players permission. One of the most popular permission plugins I know of and personally use is [LuckPerms](https://www.spigotmc.org/resources/luckperms.28140/). For more information about permission I would recommend reading this: https://luckperms.net/wiki/Home
