### ISSUE TITLE
Error message displayed in chat when running.

### ISSUE THREAD

**Issue by BlenderUser6969** [Imprex-Development/orebfuscator#268]
### Description

It seems to output this error message into chat and I don't know why. Anything I can do to fix it?

### Reproduction Steps

1. Download protocol Lib and Orebfuscator then run it on a linux debian server. 

2. The error message should just start getting spammed into chat randomly.

### Expected Behaviour

I excpect it to not output errors into Minecraft's ingame chat.

### Server Details

Spigot 1.19.2 

### Orebfuscator Version

5.3.2

### ProtocolLib Version

4.8.0

### Logs and Configs

I can't copy the chat and my linux terminal is being spammed by random errors/ outputs so I can't find it, here's a screenshot though; https://imgur.com/3hZsVQN

**Comment by Ingrim4** [comment]
1. This error has nothing to do with Orebfuscator (it's a ProtocolLib error).
2. Your using an outdated ProtocolLib version.
