### ISSUE TITLE
Error enabling

### ISSUE THREAD

**Issue by havelentzas** [Imprex-Development/orebfuscator#269]
### Description

1.19.3 error enabling obfuscator
 

### Reproduction Steps

installed most recent orebfucator and dependency

### Expected Behaviour

orebfuscator would work at preventing x ray

### Server Details

3657-Spigot-19641c7-4a929b5 (MC: 1.19.3)

### Orebfuscator Version

5.3.2

### ProtocolLib Version

4.8.0

### Logs and Configs

https://gist.github.com/Scaryharry4/e6879d3d9f5d3460d56b973eb56d3dc4

**Comment by Ingrim4** [comment]
`java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/accessors/Accessors`: ProtocolLib is missing or didn't load correctly. Try updating ProtocolLib to latest version that is compatible with 1.19+
