### ISSUE TITLE
Optimize deobfuscator for huge explosions 

### ISSUE THREAD

**Issue by Leymooo** [Imprex-Development/orebfuscator#271]
### Description

Hello, our server has custom tnts with a huge explosion radius(30 blocks), and when they explode orebfucator causes a litte lag spike (~300-500ms per explosion).

![image](https://user-images.githubusercontent.com/8667294/222620596-164119f9-1bed-4e2a-a742-839b1c1bb61b.png)

### Proposed Behaviour

Maybe deobfuscation algorithm can be optimized for explosions.

**Comment by Leymooo** [comment]
Can be optimized bu changing `hashCode` method for `BlockPos` class to
```
		int hash = 3;
		hash = 19 * hash + (int)(this.x);
		hash = 19 * hash + (int)(this.y);
		hash = 19 * hash + (int)(this.z);
		return hash;
```
Looks like current hashCode calculation is not good for HashSet, and HashSet just put all data into single node


My local testing result:
Before chaning hashCode:
![image](https://user-images.githubusercontent.com/8667294/222834655-169b0ca2-084e-4f35-bfbf-e7a5ec308567.png)

After:
![image](https://user-images.githubusercontent.com/8667294/222834873-f4cae41d-f2ac-46b8-88ec-e1af4965009e.png)

**Comment by Ingrim4** [comment]
The fact that the first screenshot you provided has 8 `TreeNode::find` calls in a single `put` operation is insane. Will be fixed in the next update.
