### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MOPEDNN** [Imprex-Development/orebfuscator#274]
### Description

plugin is not working at all

### Reproduction Steps

I tested this plugin on free hosting and it worked fine, but when I uploaded it to the main server it didn't work

### Expected Behaviour

none

### Server Details

arclight-1.19.2-1.0.1-0550c6cd

### Orebfuscator Version

5.3.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

### Logs and Configs

config is default, world name is "world"

**Comment by Ingrim4** [comment]
Need more info to reproduce your issue since it works fine for me. Please provide your full server log.

**Comment by MOPEDNN** [comment]
> Need more info to reproduce your issue since it works fine for me. Please provide your full server log.
[2023-03-10-3.log.gz](https://github.com/Imprex-Development/orebfuscator/files/10946174/2023-03-10-3.log.gz)

**Comment by Ingrim4** [comment]
Is the plugin listed if you execute the `/plugin` command and if it isn't can you turn on verbose logging in the config: [`advanced.verbose`](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#advanced) and send the log with it turned on. Also make sure you don't have the `orebfuscator.bypass` permission.

Please use this version: https://github.com/Imprex-Development/orebfuscator/suites/11318200303/artifacts/581280978 of Orebfuscator for better verbose logging.

**Comment by Ingrim4** [comment]
Just checked out `arclight` they are using different world name then default bukkit does: `world/DIM-1` is `world_nether` and `world/DIM1` is `world_the_end`. So if Orebfuscator didn't work in the nether or end for you then simply adding these world names to the config should fix your issue.
