### ISSUE TITLE
1.16.5 stuck in place chunks not loading

### ISSUE THREAD

**Issue by umbreontk** [Imprex-Development/orebfuscator#278]
### Description

im using this on my 1.16.5 arclight server on aternos but when ever i load in the world is unloaded and its not loading at all when i use the reload command to reload the plugin it works fine until i walk into a new chunk then it repeats the same process again

### Reproduction Steps

1 start up server

2 join server

3 results 

### Expected Behaviour

a simple anti xray to do as its supposed to do 

### Server Details

1.16.5 (1109) arclight

### Orebfuscator Version

5.3.3

### ProtocolLib Version

4.8.0

**Comment by NgLoader** [comment]
Can you provide some more information please?
- Console Log
- Mods

#
Have you already checked this issue? https://github.com/Imprex-Development/orebfuscator/issues/274#issuecomment-1464530853

**Comment by umbreontk** [comment]
oh sure let me get the logs rq and mod wise there are quite a few

**Comment by Ingrim4** [comment]
closed due to inactivity
