### ISSUE TITLE
error massage

### ISSUE THREAD

**Issue by ShotariGame** [Imprex-Development/orebfuscator#279]
### Description

hello I have this error message that appears in the console and in minecraft I follow in 1.19.4

 Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@2b529e3b[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@48df0592
      player=CraftPlayer{name=ShotariCute}
      updated=<null>
      playerName=ShotariCute
      playerConnection=net.minecraft.server.network.PlayerConnection@2670a1c
      networkManager=net.minecraft.network.NetworkManager@19df341b
      originalChannel=[id: 0x9725ffe4, L:/172.18.0.27:25222 - R:/90.29.118.121:60021]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@19df341b, previous=[id: 0x9725ffe4, L:/172.18.0.27:25222 - R:/90.29.118.121:60021], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@29974343, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4c686857
      vanillaDecoder=net.minecraft.network.PacketDecoder@2c77f22d
      vanillaEncoder=net.minecraft.network.PacketEncoder@67101710
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5e1e7ba3
      processor=com.comphenix.protocol.injector.NetworkProcessor@7bab39fc
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@3264ac6
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.5
  Server:
    3673-Spigot-41150f3-703575f (MC: 1.19.4)

### Reproduction Steps

I installed the latest version of Proctolib and Orebfuscator on the site

### Expected Behaviour

I'm a beginner and I don't know how to solve the problem

### Server Details

Spigot 1.19.4

### Orebfuscator Version

5.3.3

### ProtocolLib Version

4.8.0

**Comment by NgLoader** [comment]
You need to use the latest dev build from ProtocolLib

**Comment by Ingrim4** [comment]
closed due to inactivity
