### ISSUE TITLE
Many Lags 

### ISSUE THREAD

**Issue by ghost** [Imprex-Development/orebfuscator#28]
Latest Orebfuscator Version for 1.16 lags like hell.

Spigot 1.16.1 and latest Dev Version from Protocollib. 

Protocollib shows errors to

Your Versions for 1.15 was really good. But this lags. Or is it protocollib?

React shows me High spikes from Orebfuscator  and protocollib

**Comment by Ingrim4** [comment]
Could you upload the log or an exception and tell me if you changed something in the config so we can investigate your problem. [Timings](https://www.spigotmc.org/wiki/timings/) would also help.
