### ISSUE TITLE
Long world/terrain loading + no terrain display.

### ISSUE THREAD

**Issue by BartosB13** [Imprex-Development/orebfuscator#282]
### Description

I don't know what could be causing it. I've been looking for a solution to the problem myself, but to no avail. Do you have any idea what could be causing this?

Loading the world takes a long time, and then you literally can't see anything, there is also a problem with camera movement

Screenshot below.

### Reproduction Steps

Entering the server

### Expected Behaviour

Correct terrain display

### Server Details

Paper 448 1.19.3

### Orebfuscator Version

5.3.3

### ProtocolLib Version

5.0.0 SNAPSHOT-b616

### Logs and Configs

No errors in the console

### Extra Details

![image](https://user-images.githubusercontent.com/89303317/231569432-0a6de61d-ab1f-4676-a062-3e13a6dacae6.png)

**Comment by BartosB13** [comment]
Another strange problem. When I remove the plugin from the plugins folder, the server can't start completely and at some point it stops and nothing happens (no errors)

Can another plugin cause this problems?

**Comment by NgLoader** [comment]
Orebfuscator is only modifing packets and didnt change anything else on your server (that coudht produce only clientside bugs).

After Orebfuscator is no longer in your plugins folder it will no longer be possible to load it on startup.
You can try to disable protocollib and maybe check if anything is broken in your currently protocollib version.

Could you also please provide a list of your currently used plugins.

**Comment by BartosB13** [comment]
I managed to fix the problem, I don't know what exactly caused it, most likely some plugin that I updated. Anyway, thank you very much for your help, it put me on the right track.
