### ISSUE TITLE
not allows bedrock joins

### ISSUE THREAD

**Issue by mozzz14** [Imprex-Development/orebfuscator#289]
### Description

when this plugin is used it makes bedrock players disconnect instantly and wont let them join. im running a paper java server with geyser and floodgate running

### Reproduction Steps

have installed

### Expected Behaviour

for both players to join properly 

### Orebfuscator Dump

https://gist.github.com/mozzz14/ec2c49f0e48657a64bb3dab123f369a9

### Extra Details

this plugin works fine with bedrock players joining a java server on any other world just not the one i want it on

**Comment by Ingrim4** [comment]
According to your dump file you don't even have Orebfuscator enabled. Can you please make sure that Orebfuscator is running properly on your server and attach an Orebfusactor dump file (`/orebfuscator dump`)

**Comment by mozzz14** [comment]
weird i reinstalled it and now it works fine. allowing play from both. if it happens again ill reopen an issue

**Comment by mozzz14** [comment]
nevermind, stopped again

https://gist.github.com/mozzz14/3d716f6f079ac989c6dcc950292f1724

**Comment by mozzz14** [comment]
?

**Comment by NgLoader** [comment]
I'm unable to reproduce your error.
Can you please provide a video of your issue?

I tested it with Geyser on Bungeecord and Spigot, with Orebfuscator, ProtocolLib, ViaVersion, ViaRewind, and ViaBackwards enabled and with your provided config file.
I also tried it with the Java and Bedrock editions, and everything works fine.

**Comment by NgLoader** [comment]
I also tryed it with GrimAC v2.3.40 without any issues

**Comment by mozzz14** [comment]
With a reinstall it works normally up to 5/10mins then just stops every time. I cant provide a video right now but in about 10hours i can. You can try to connect with bedrock and it just wont let you, put in direct connect: 193.70.34.168:25608

**Comment by NgLoader** [comment]
> With a reinstall it works normally up to 5/10mins then just stops every time. I cant provide a video right now but in about 10hours i can. You can try to connect with bedrock and it just wont let you, put in direct connect: ****

Please don't provide your current IP address.
For something like that, please contact us directly and don't share it with everyone.

I just tested it with Bedrock on your server for about 20-25 minutes without any issues.
What kind of stuff do you do there to process this issue?

**Comment by mozzz14** [comment]
were you LetMeCodeIt? It said you joined on a java client, not bedrock. Also it wasnt my ip just the public server ip. And for me to recreate it i just try to join on a bedrock client. We could get in a discord call so i could show you from my phone account and pc bedrock

**Comment by mozzz14** [comment]
here is a video of it not working 
https://youtu.be/vEYj8ZY4i_s

**Comment by NgLoader** [comment]
> were you LetMeCodeIt? It said you joined on a java client, not bedrock. Also it wasnt my ip just the public server ip. And for me to recreate it i just try to join on a bedrock client. We could get in a discord call so i could show you from my phone account and pc bedrock

I joined with the Bedrock client on Windows. 
You can find me on discord under **ngloader**

**Comment by mozzz14** [comment]
got into discord call and sorted it. the fix was reducing the amount of ores it obfuscated with. it was kicking due to bedrock sending too big packets

**Comment by NgLoader** [comment]
This can happens when your operating system has set the MTU value to small (or the firewall is being picky). This results in blocked packets.

Issue related to this kind: https://github.com/PowerNukkit/PowerNukkit/issues/1056#issuecomment-843199889
