### ISSUE TITLE
I'm sorry, but how must i install it for spigot 1.15.2, i don't see extension.Jar..

### ISSUE THREAD

**Issue by darkvenger34** [Imprex-Development/orebfuscator#29]
I'm sorry, but how must i install it for spigot 1.15.2, i don't see extension.Jar.
can u say what must i do for download it xd
usually i must just drag the file.Jar into the plugins, but i can't find that.

**Comment by NgLoader** [comment]
Here [Download](https://github.com/Imprex-Development/Orebfuscator/releases/download/v5.0.0-v16-pre/orebfuscator-plugin-v5.0.0-v16-pre.jar)

**Comment by NgLoader** [comment]
And you need ProtocolLib (latest)
