### ISSUE TITLE
OreBFuscator 5.4.0 (1.20)

### ISSUE THREAD

**Issue by breezefps** [Imprex-Development/orebfuscator#292]
### Description

Try to add my OreBFuscator plugin to my Spigot 1.20 server and It's getting this erro in the console when turning on, the plugin get's red in the /pl and disabled as well.
![notepad++_U6g2ezVYqO](https://github.com/Imprex-Development/orebfuscator/assets/51733120/a476381f-a82d-43e6-b972-4293d87c88dc)

### Reproduction Steps

I just moved the jar to a 1.20 spigot server on the plugin files. (ProtocolLIB Updated as well.)

### Expected Behaviour

Working because it pl was updated to the 1.20 version

### Orebfuscator Dump

not able to run this command because it's not working for me.
link: https://i.imgur.com/lardBJo.png

**Comment by NgLoader** [comment]
It seems you have a wrong config.
Delete or rename your currently orebfuscator config and try it again, Orebfuscator will create a own config file.

**Comment by breezefps** [comment]
> It seems you have a wrong config. Delete or rename your currently orebfuscator config and try it again, Orebfuscator will create a own config file.

![image](https://github.com/Imprex-Development/orebfuscator/assets/51733120/a68665d5-3f89-4ec4-83f7-c25daf501db0)
FIXED! TYY!
