### ISSUE TITLE
server loading time takes ages 

### ISSUE THREAD

**Issue by Robo5626** [Imprex-Development/orebfuscator#294]
### Description

when we added it and got if fixed when we restarted and logged in it takes ages and sometimes doesnt load 

### Reproduction Steps

we installed it change world name files on config to get it working and wen we relog it laggs and takes ages 

### Expected Behaviour

load in normally 

### Orebfuscator Dump

[dump-2023-06-10_18.37.26.zip](https://github.com/Imprex-Development/orebfuscator/files/11713072/dump-2023-06-10_18.37.26.zip)

### Extra Details

we disabled it so we could load in normal again can you help

**Comment by Ingrim4** [comment]
I'm not sure what you are referring to with "doesn't load" but I would guess you mean the chunks/world doesn't load when you join. If that's the case you could set the `useAsyncPacketListener` option to `false`  in the config see if that fixes it. If it doesn't then I would ask you to run the [spark](https://www.spigotmc.org/resources/spark.57242/) profiler on your server and share a report of it with us.

1. put `spark` on your server
2. run `/spark profiler start`
3. join and leave the server a few time
4. run `/spark profiler stop`
5. share the spark report link to us

**Comment by Ingrim4** [comment]
Closed due to inactivity
