### ISSUE TITLE
Teleports usually mess up stuff

### ISSUE THREAD

**Issue by Texbio** [Imprex-Development/orebfuscator#298]
### Description

Hello, is it possible to make blocks update on teleport? 

When teleporting somewhere, it is really annoying when your player is glitching out because your home is set on a specific block. This already happens on re-login and other events so why not teleports?

### Proposed Behaviour

Load blocks on teleports

### Extra Details

I am not sure how teleports are detected but it should be possible to add this in.

**Comment by Ingrim4** [comment]
We already have a working prototype that completely abandoned events for proximity deobfuscation which has a configurable check interval for all players with a changed position (`advanced.proximityThreadCheckInterval`) and one for players regardless of change in position (`advanced.proximityPlayerCheckInterval`). Meaning every player should get updates sooner or later regardless of events. This is already part of our `master` branch so you could try the early version in our Github actions in the `Artifacts` section: https://github.com/Imprex-Development/orebfuscator/actions/runs/5235888122

**Comment by Ingrim4** [comment]
Fixed in latest release
