### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by pogrammerx** [Imprex-Development/orebfuscator#301]
### Description

I put the plugin into my plugins folder, i didnt change the config, no errors in the console and yet its not working, my world is just called "world" and the blocks are not getting obfuscated. Any help is appreciated. Im Running Spigot 1.20 and Orebfuscator 5.4.0

### Reproduction Steps

Install the plugin on a Spigot 1.20 server

### Expected Behaviour

I expected the plugin to stop XRaying, it didnt work

### Orebfuscator Dump

https://gist.github.com/pogrammerX/dbc9466c225bd595de799554377251c7

**Comment by Ingrim4** [comment]
What do you mean by it didn't work? Where you able to still see ores or did you game/server crash/disconnect? Did it happen with a bedrock or java game client? Have you tried it without floodgate/geyser?

**Comment by Ingrim4** [comment]
Closed due to inactivity
