### ISSUE TITLE
Kick from server after change dimensions

### ISSUE THREAD

**Issue by VanyaNexus** [Imprex-Development/orebfuscator#302]
### Description

When I teleport from the end world to the normal world, I get kicked from the server.

### Reproduction Steps

1) Launching the server 1.19.2, I have a multipaper modification, but I don’t think it has much effect
2) Login with client 1.16.5
3) Go to the end portal
4) I teleport to the normal world with the /spawn command (I checked teleports to different positions, the result is the same)
5) I was kicked from the server

### Expected Behaviour

I didn't get kicked

### Orebfuscator Dump

https://gist.github.com/VanyaNexus/c3a0920719738d1e9aeaf5d3107c70f4

**Comment by VanyaNexus** [comment]
The same problem without modifying multipaper and on the server paper 1.19.2

**Comment by Ingrim4** [comment]
Could you test if a pure paper server without any extra plugins/modifications (only Orebfuscator and ProtocolLib) has the same problem with your world?

**Comment by VanyaNexus** [comment]
Checked. This is present when the viaversion is installed and even if I am on the server from the client version 1.16.5

**Comment by VanyaNexus** [comment]
How to fix this?

**Comment by Lumeloti** [comment]
Was a solution found to the problem?

**Comment by Ingrim4** [comment]
Yeah sorry I probably forgot to write something when closing this as it took me a while to process why I closed this:

As of now we have no plans to support multipaper that's why I closed this.

**Comment by VanyaNexus** [comment]
I wrote that this problem was not only with multipaper. The solution to the problem was updating viaversion

**Comment by Lumeloti** [comment]
This problem is also observed on the purpur server. Of the plugins, only orebfuscator and protocollib. Everything else is standard.
Later I will create a separate detailed issue on this topic*
