### ISSUE TITLE
RealisticSeasons Compatibility

### ISSUE THREAD

**Issue by Futodama** [Imprex-Development/orebfuscator#303]
### Description

After updating the plugin to the latest version, it seriously began to conflict with the RealisticSeasons plugin.

It redefines biomes that superimpose RealisticSeasons on top of the regular world.

I ask you to correct this error, but at the same time the plugin should change its appearance according to the season, at the moment it does not change its color scheme, but only some chunks undergo some kind of replacement.

### Reproduction Steps

1) Install minecraft server 1.20.1
2) Install RealisticSeasons
3) Install Orebfuscator

### Expected Behaviour

Behavior: When you turn on a season other than summer, the game world does not accept the color scheme set by the plugin for trees and grass.

### Orebfuscator Dump

https://gist.github.com/Futodama/03a7dc379749841d74926d9052a3308b
[dump-2023-07-27_13.51.12.txt](https://github.com/Imprex-Development/orebfuscator/files/12182450/dump-2023-07-27_13.51.12.txt)

### Extra Details

ver ProtocolLib
[13:53:53 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-660
[13:53:53 INFO]: Provides read/write access to the Minecraft protocol.
[13:53:53 INFO]: Authors: dmulloy2 and comphenix
ver RealisticSeasons
[13:54:01 INFO]: RealisticSeasons version 10.5.8
Orebfuscator
[13:54:06 INFO]: You are using Orebfuscator v5.4.0
ver
[13:54:13 INFO]: Current: git-Purpur-2019 (MC: 1.20.1)*
Previous: git-Purpur-2005 (MC: 1.20.1)
* You are running the latest version

**Comment by Futodama** [comment]
https://wiki.realisticseasons.com/developers/api

Here is their API

**Comment by Futodama** [comment]
Please do not ignore this problem, the plugin is used on many servers of the RP and RPG genre.

**Comment by JasperTheMinecraftDev** [comment]
For clarity, RealisticSeasons injects custom biomes in the biome packets and I think that OreObfuscator is overriding them.
He means that the custom biomes are not sent to the client at all, therefore the colors are not applied.

Also, a note on the RS API: You need the paid plugin jar to use it, if you join our discord and DM Kapstok, he can probably give it to you for free, because you're using it for developing.

**Comment by Ingrim4** [comment]
I have contacted Kapstock and we will start looking into this issue once I have a reply.

**Comment by Futodama** [comment]
> I have contacted Kapstock and we will start looking into this issue once I have a reply.

Exelent!

**Comment by Ingrim4** [comment]
I've tried to implement a fix into ProtocolLib could you check if that fixes the issue: https://github.com/Imprex-Development/ProtocolLib/releases/tag/5.0.0-fix

**Comment by Futodama** [comment]
> I've tried to implement a fix into ProtocolLib could you check if that fixes the issue: https://github.com/Imprex-Development/ProtocolLib/releases/tag/5.0.0-fix

Nothing has changed. These plugins do not work together. The foliage has not been updated.

**Comment by Ingrim4** [comment]
Should be fixed as of latest ProtocolLib dev-build [ProtocolLib#2503](https://github.com/dmulloy2/ProtocolLib/pull/2503).
