### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by Ortuah** [Imprex-Development/orebfuscator#304]
### Description

The Plugin simply doesn't work. When I drag it into the Plugin folder and restart the Server, it doesn't install. When I enter "/plugins" in game, the Plugin name is red. 

### Reproduction Steps

Drag it into the Plugin folder and restart the Server.

### Expected Behaviour

It should work :)

### Orebfuscator Dump

-

**Comment by Ortuah** [comment]
Please help

**Comment by NgLoader** [comment]
Please provide an Orebfuscator dump file (use /orebfuscator dump) or if Orebfuscator didn't start provide a ProtocolLib dump (use /protocol dump). You should use https://gist.github.com/ to upload, then include the link below.

**Comment by NgLoader** [comment]
Closed due to inactivity
