### ISSUE TITLE
the plugin is off 

### ISSUE THREAD

**Issue by faxo22** [Imprex-Development/orebfuscator#312]
### Description

when im on the game and i write /plugin Orebfuscator is in red but all my other plugin are in green and when i try my xray the Orebfuscator do nothing because i can xray

### Reproduction Steps

Install the plugin on a bukkit1.20 server

### Expected Behaviour

I expected the plugin to stop XRaying, it didnt work

### Orebfuscator Dump

24.08 14:54:18 [Server] WARN Unexpected exception while parsing console command "orebfuscator dump"
24.08 14:54:18 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'orebfuscator' in plugin Orebfuscator v5.3.4 - plugin is disabled.
24.08 14:54:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
24.08 14:54:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
24.08 14:54:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-160]
24.08 14:54:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:970) ~[paper-1.20.1.jar:git-Paper-160]
24.08 14:54:18 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.1.jar:git-Paper-160]
24.08 14:54:18 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.1.jar:git-Paper-160]
24.08 14:54:18 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-160]
24.08 14:54:18 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-160]
24.08 14:54:18 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-160]
24.08 14:54:18 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Extra Details

no response

**Comment by NgLoader** [comment]
Have you installed ProtocolLib?

**Comment by faxo22** [comment]
yes

**Comment by NgLoader** [comment]
Can you provide the server version?
Please use the following command: ``/version``

**Comment by faxo22** [comment]
they said im in a late version how do i change it?


25.08 17:45:43 [Server] INFO This server is running Paper version git-Paper-160 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b8a0049)
25.08 17:45:43 [Server] INFO You are 3 version(s) behind
25.08 17:45:43 [Server] INFO Download the new version at: https://papermc.io/downloads/paper
25.08 17:45:43 [Server] INFO Previous version: git-Paper-9 (MC: 1.20)

**Comment by faxo22** [comment]
this is what i see when im on the game and a type /plugins

 [
![2023-08-25_23 46 38](https://github.com/Imprex-Development/orebfuscator/assets/143105908/4d9e1808-a809-4fe8-97f4-28b870ec0913)
](url)

**Comment by PetyXbron** [comment]
@faxo22 your Orebfuscator is not working because **ProtocolLib is not working** too (from your screenshot).
Could you check your ProtocolLib version (if it supports your server version and software [Paper, Purpur, etc.])?
For the latest MC version of your server use [the latest ProtcolLib version](https://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/).
For more fixing of your issue, you can take a look at [the ProtocolLib Spigot resource page](https://www.spigotmc.org/resources/protocollib.1997/) or/and [the GitHub repository](https://github.com/dmulloy2/ProtocolLib/).
