### ISSUE TITLE
Paper 1.20.1 

### ISSUE THREAD

**Issue by monkeyadece** [Imprex-Development/orebfuscator#313]
### Description

I'm using paper and I tried reinstalling it, the Anti-xray isn't working. No errors, it loads but it doesn't work?

### Reproduction Steps

Install paper.

### Expected Behaviour

It used to work on spigot, but not anymore?

### Orebfuscator Dump

I reinstalled it.

### Extra Details

* No.

**Comment by Ingrim4** [comment]
Please provide an Orebfuscator dump file (use `/orebfuscator dump`) or if Orebfuscator didn't start provide a ProtocolLib dump (use `/protocol dump`). You should use https://gist.github.com/ to upload, then include the link below.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
