### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TImotheus23-hub** [Imprex-Development/orebfuscator#314]
### Description

i have installed ProtocolLib.jar and orebfuscator-plugin-5.4.0.jar

xray still works and when i use _/ofc_ it says:  **[dump]**
and the same for all of the _/orebfuscator_ commands

### Reproduction Steps

installed ProtocolLib.jar and orebfuscator-plugin-5.4.0.jar

### Expected Behaviour

i expect it to stop xray as it says in
https://dev.bukkit.org/projects/orebfuscator-anti-x-ray 
Orebfuscator is a plugin for Spigot based Minecraft Servers that modifies packets in order to hide blocks of interest from X-Ray Clients and Texture Packs. Thus it doesn't modify your world and is safe to use.​_

### Orebfuscator Dump

![image](https://github.com/Imprex-Development/orebfuscator/assets/111846761/42d1fdf6-4cda-4a49-887a-64c52059aa75)

**Comment by Ingrim4** [comment]
Please provide an Orebfuscator dump file (use `/orebfuscator dump`) or if Orebfuscator didn't start provide a ProtocolLib dump (use `/protocol dump`). You should use https://gist.github.com/ to upload, then include the link below.

**Comment by TImotheus23-hub** [comment]
![image](https://github.com/Imprex-Development/orebfuscator/assets/111846761/2f64ee9e-103d-4a41-92af-30f4110dcebc)
![image](https://github.com/Imprex-Development/orebfuscator/assets/111846761/9372c0b7-fded-4c00-8483-8f8d513c4f46)

so **/orebfuscator dump** did nothing
were is a screenshot with xray on
![image](https://github.com/Imprex-Development/orebfuscator/assets/111846761/12fab785-1486-4071-9dbd-7c033786dd7c)

**Comment by Ingrim4** [comment]
Sorry we can't help you without the Orebfuscator dump file either provide it or a ProtocolLib dump. If you can't we can't help you!

**Comment by TImotheus23-hub** [comment]
there is no Orebfuscator dump file
even if i go in plugins folder Orebfuscator hasnt made a folder for itself?
what do i do?

heres the protocal dump
![image](https://github.com/Imprex-Development/orebfuscator/assets/111846761/47fba497-a896-471e-9b96-4f805a361a0c)

**Comment by NgLoader** [comment]
You need to execute the right command ``/orebfuscator dump``. Please check your console log if any errors appear from Orebfuscator or ProtocolLib and repost them here.

**Comment by TImotheus23-hub** [comment]
so it just says when i use **/orebfuscator dump**
_[13:51:59] [Server thread/INFO]: chokatimo issued server command: /orebfuscator dump_

and when i use **/protocol dump** it says
_[13:51:59] [Server thread/INFO]: chokatimo issued server command: /orebfuscator dump_

**Comment by Ingrim4** [comment]
Can you please simply upload your whole log cause this isn't helpful.

**Comment by Bete1488** [comment]
so, ok, I deleted the config, restarted the server, and now anti Xray is "true" but it still doesn't do anything on the server

**Comment by Ingrim4** [comment]
Closed due to inactivity.
