### ISSUE TITLE
Chunks break

### ISSUE THREAD

**Issue by nafech** [Imprex-Development/orebfuscator#315]
### Description

The chunks break when using orebfuscator (check screenshot) ![2023-09-01_22 12 56](https://github.com/Imprex-Development/orebfuscator/assets/143841122/280cc644-b94d-4357-b803-a115c5c24364)

### Reproduction Steps

Install your own plugin on the server and the whole world breaks 💀

### Expected Behaviour

Um, I expected the world **not** to break 💀

### Orebfuscator Dump

https://gist.github.com/nafech/50c1308fcb779df09f9006d7e038bc5f

**Comment by Ingrim4** [comment]
It's impossible for Orebfuscator to break the world as it doesn't interact or change the world so this is either just your world, another plugin or minecraft itself.
