### ISSUE TITLE
Server CRASH - errors.

### ISSUE THREAD

**Issue by sm1leclock** [Imprex-Development/orebfuscator#331]
### Description

Such an error with crash and prologue periodically occurs on the server. 
https://pastebin.com/bXnaNMt9

### Reproduction Steps

While the server is running

### Expected Behaviour

The server suddenly freezes and a freeze occurs

### Orebfuscator Dump

The server is clean and this was not the case in previous updates - it was noticed only in the latest ones.

**Comment by Ingrim4** [comment]
From the part of your log that you send it looks like this happened when tnt exploded and it tried to deobfuscate (can you confirm that). Can you please provide an Orebfuscator dump file (use `/orebfuscator dump`) and uploaded it to https://gist.github.com/. Furthermore could you please provide us with a [spark profiler](https://www.spigotmc.org/resources/spark.57242/) report:

1. put `spark` on your server
2. run `/spark profiler start`
3. try to recreate the issue described
4. run `/spark profiler stop`
5. share the spark report link with us

**Comment by Ingrim4** [comment]
Closed due to inactivity.
