### ISSUE TITLE
Loading failed

### ISSUE THREAD

**Issue by Davidx01** [Imprex-Development/orebfuscator#332]
### Description

hi, orebfuscator is tuck on loading (i have protocol lib)

### Reproduction Steps

starting the server

### Expected Behaviour

the server doesn't start orebfuscator

### Orebfuscator Dump

i can't use the plugin in game

### Extra Details

[24Oct2023 18:58:12.826] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Orebfuscator v5.4.2 (Is it up to date?)
--
414 | java.lang.NoSuchFieldError: AIR
415 | at net.imprex.orebfuscator.nms.v1_20_R1_mojang.NmsManager.<clinit>(NmsManager.java:45) ~[?:?] {}
416 | at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin,re:mixin}
417 | at java.lang.Class.forName(Class.java:467) ~[?:?] {re:mixin,re:mixin}
418 | at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_5.redirectClassForName(ArclightReflectionHandler.java:234) ~[arclight-1.20.1-1.0.2-SNAPSHOT-71acd73.jar%23178!/:arclight-1.20.1-1.0.2-SNAPSHOT-71acd73] {}
419 | at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_5.redirectClassForName(ArclightReflectionHandler.java:227) ~[arclight-1.20.1-1.0.2-SNAPSHOT-71acd73.jar%23178!/:arclight-1.20.1-1.0.2-SNAPSHOT-71acd73] {}
420 | at net.imprex.orebfuscator.OrebfuscatorNms.initialize(OrebfuscatorNms.java:37) ~[?:?] {}
421 | at net.imprex.orebfuscator.config.OrebfuscatorConfig.deserialize(OrebfuscatorConfig.java:137) ~[?:?] {}
422 | at net.imprex.orebfuscator.config.OrebfuscatorConfig.load(OrebfuscatorConfig.java:60) ~[?:?] {}
423 | at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:54) ~[?:?] {}
424 | at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:52) ~[?:?] {}
425 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.2-SNAPSHOT-71acd73.jar%23178!/:arclight-1.20.1-1.0.2-SNAPSHOT-71acd73] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
426 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.2-SNAPSHOT-71acd73.jar%23178!/:arclight-1.20.1-1.0.2-SNAPSHOT-71acd73] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
427 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.2-SNAPSHOT-71acd73.jar%23178!/:arclight-1.20.1-1.0.2-SNAPSHOT-71acd73] {re:mixin,re:classloading,re:mixin}
428 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.2-SNAPSHOT-71acd73.jar%23178!/:arclight-1.20.1-1.0.2-SNAPSHOT-71acd73] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
429 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.2-SNAPSHOT-71acd73.jar%23178!/:arclight-1.20.1-1.0.2-SNAPSHOT-71acd73] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
430 | at net.minecraft.server.MinecraftServer.handler$zda000$arclight$enablePlugins(MinecraftServerMixin.java:2137) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
431 | at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
432 | at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
433 | at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
434 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
435 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
436 | at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin,re:mixin,re:mixin}

</body>
</html>

**Comment by Davidx01** [comment]
when would be fixed that?

**Comment by Ingrim4** [comment]
I won't push an update for this yet since this only affects arclight which isn't officially supported and tested by use. In the mean you can use the build artifacts from our github actions pipeline: https://github.com/Imprex-Development/orebfuscator/actions/runs/6646315279
