### ISSUE TITLE
Not loading switching dimensions 

### ISSUE THREAD

**Issue by PozaiTheEnforcer** [Imprex-Development/orebfuscator#334]
### Description

I have read your issue reports. I know you know this is a problem, and looking at a few of them you guys never provide a solution. So I decided to also make a bug report because if it’s constantly being brought up you can’t just ignore it again. When going through nether portal, joining the game, or teleporting it makes you fall through the world and doesn’t load the game 

### Reproduction Steps

Go through nether portal

### Expected Behaviour

Falling through the world, nothing loading

### Orebfuscator Dump

I don’t need to because other people’s bug reports have done it enough. You guys know the problem, fix it

### Extra Details

Please actually fix this issue

**Comment by Ingrim4** [comment]
First of all it's not something we are ignoring it's just something we didn't know how to fix at the time. Secondly it's not our bug it's a bug with ProtocolLib's async packet listener and I already submitted a pull request to fix this (https://github.com/dmulloy2/ProtocolLib/pull/2545). So don't just assume stuff that's rude (also this is just a hobby project so I'm technically not obligated to do anything and the beauty of FOSS is you can just fork the code and change the code yourself if you so desire).

P.S.
Have you tried our temporary fix proposed on our [Common Issues (Some/all chunks aren't sent/rendered)](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues#someall-chunks-arent-sentrendered-world-appears-empty) page and does it fix the issue?

**Comment by Ingrim4** [comment]
Closed due to inactivity.
