### ISSUE TITLE
Repeated IllegalPluginAccessException on Server Shutdown with Orebfuscator Plugin

### ISSUE THREAD

**Issue by DimaSergeew** [Imprex-Development/orebfuscator#338]
### Description

The server consistently encounters an IllegalPluginAccessException during shutdown. This issue arises specifically with the Orebfuscator plugin version 5.4.2-b274. The error indicates that the plugin attempts to register a task while it is disabled. The server operates normally until the shutdown process initiates, at which point these exceptions are repeatedly logged.

### Reproduction Steps

1. Start the server with Orebfuscator plugin version 5.4.2-b274 installed.
2. Operate the server normally.
3. Initiate server shutdown.
4. Observe the logged errors during the shutdown process.

### Expected Behaviour

The server should shut down without encountering IllegalPluginAccessExceptions, and the Orebfuscator plugin should not attempt to register new tasks during or after the shutdown process.

### Orebfuscator Dump

[dump-2023-12-02_10.23.04.json](https://github.com/Imprex-Development/orebfuscator/files/13535940/dump-2023-12-02_10.23.04.json)

### Extra Details

- Minecraft Server Version: [specify your server version, e.g., 1.20]
- CraftBukkit Version: v1_20_R2
- Error Log: [Include the error log snippet you provided, or attach the full log file if possible]
- Log error: https://mclo.gs/fGBZoIv

**Comment by Ingrim4** [comment]
Should be fixed with the latest dev build (https://github.com/Imprex-Development/orebfuscator/actions/runs/6991822743).
