### ISSUE TITLE
if teleport player in other world - player freeze and errors in console

### ISSUE THREAD

**Issue by SL-69** [Imprex-Development/orebfuscator#343]
### Description

if teleport player in other world - player freeze and errors in console while player in game (relogin - resolve)

### Reproduction Steps

1. server - paper 1.12.2 (latest build)
2. enter in end (for example) and other account in world 
3. tp account 2 (in world) in end
4. maybe (not always) player freeze and console errors

### Expected Behaviour

work without errors and player tp without freeze

### Orebfuscator Dump

https://gist.github.com/Tioplaya/b8ecd37df18ed555ca76b7c0cc5ffb91

### Extra Details

player freeze all (fly after tp and all actions on player don't act)

**Comment by NgLoader** [comment]
Can you please provide the console errors and check if the same issue occurs if you remove/disable `ViaVersion`?

**Comment by SL-69** [comment]
I found out the reason: if you teleport from world to world (from world to nether from nether to end), then during fast teleportation this error occurs. Verified without viaversion

**Comment by Ingrim4** [comment]
You please provide us the server log file or the error?

**Comment by SL-69** [comment]
weird, I think I attached a link, here it is again - https://logpaste.com/uuuNEDGp

**Comment by Ingrim4** [comment]
The error can only occur if the chunk packets we receive from the server or other plugins are using an invalid format that isn't the default one mojang uses. I can't see any other plugins that are modifying chunk packets with ProtocollLib so I would ask you to please try to replicate this with a clean paper server (only ProtocolLib and Orebfuscator) and the same world. If you should encounter the issue with a clean paper setup then the world is at fault (highly unlikely) otherwise it's an incompatibility with a plugin that modifies chunks packets without ProtocolLib.

**Comment by SL-69** [comment]
![2024-01-02_14 40 15](https://github.com/Imprex-Development/orebfuscator/assets/137718036/66510916-0516-4c94-9a28-7c6ebc4f8aa3)
![image](https://github.com/Imprex-Development/orebfuscator/assets/137718036/021af9e1-a4e9-4d6d-8709-a531ad68745b)
Tested on an empty server. Only Essentials, Orebfuscator and Protocolib are installed. I just wanted to load chunks for teleporting the second player and I get this error. the blocks freeze, just like me, when teleporting I don’t see anything. look at my config, maybe I did something wrong or am overloading the plugin with blocks - https://logpaste.com/LxNNhAW1

**Comment by SL-69** [comment]
when teleporting quickly, the player freezes for a few seconds
![2024-01-02_14 48 57](https://github.com/Imprex-Development/orebfuscator/assets/137718036/82831371-9475-48fb-a168-bd279401d874)

**Comment by Ingrim4** [comment]
Could also be related to this open PR [ProtocolLib#2545](https://github.com/dmulloy2/ProtocolLib/pull/2545) that mostly effects older version of the game. You could try to disable the `advanced.useAsyncPacketListener` ([here](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#advanced)) in your config and check if that fixes it. If that fixes your issue then it's related to the PR and should be fixed without the option disabled in a new version of ProtocolLib.
