### ISSUE TITLE
OreObfuscator doesnt work on 1.20.4

### ISSUE THREAD

**Issue by NotKNow21Br** [Imprex-Development/orebfuscator#344]
### Description

IT Says Cant load when i try to use /oreobfuscator command and there's no files on plugins folder

### Reproduction Steps

just install it with protocolib

### Expected Behaviour

to work

### Orebfuscator Dump

cant cause no commands of orebfuscator works

**Comment by NgLoader** [comment]
Can you please provide some more informations about what server version your currently using ``/version`` and are there any console errors?

And what is your Orebfuscator and ProtocolLib version?

**Comment by Krithiv-7** [comment]
Facing same issue 

This server is running Paper version git-Paper-385 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8c8862f)
You are running the latest version

Orebuscator version 5.4.3
ProtocolLib version 5.1.0

Even Orebuscator Folder isn't created.

**Comment by NgLoader** [comment]
> Facing same issue
> 
> This server is running Paper version git-Paper-385 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8c8862f) You are running the latest version
> 
> Orebuscator version 5.4.3 ProtocolLib version 5.1.0
> 
> Even Orebuscator Folder isn't created.

You need to use the latest dev build from [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/) since older versions don't support 1.20.4. Your server log should also contain the following error message: `ProtocolLib can't be found or is disabled! Orebfuscator can't be enabled.`

**Comment by Krithiv-7** [comment]
As of working with beta release it worked, thanks!
