### ISSUE TITLE
not working for me when i download to my server i dont get any config and no commands work

### ISSUE THREAD

**Issue by callmeanidiot** [Imprex-Development/orebfuscator#345]
### Description

i added the plugin to my server but when i try run a command fromt the plugin it says an internal error occurred same happens for protocallib and when i check for the orebfuscator files i dont find any 

### Reproduction Steps

i just tried downloading it and this happened

### Expected Behaviour

to work

### Orebfuscator Dump

cant get the command

### Extra Details

![Screenshot 2024-01-13 120953](https://github.com/Imprex-Development/orebfuscator/assets/59388985/3870b40a-73e9-46fe-aa04-383c93782793)

**Comment by Ingrim4** [comment]
Did you make sure to use the latest ProtocolLib [DevBuild](https://ci.dmulloy2.net/job/ProtocolLib/)? Please check your server logs to make sure that ProtocolLib got enabled correctly.

**Comment by callmeanidiot** [comment]
yeah that worked thanks
