### ISSUE TITLE
Not hidding spawners and players heads

### ISSUE THREAD

**Issue by alexmircea27** [Imprex-Development/orebfuscator#349]
### Description

I dont find a way to hide spawners and cutom player heads 

### Reproduction Steps

-

### Expected Behaviour

-

### Orebfuscator Dump

https://gist.github.com/alexmircea27/b6572079cfb3a0fcee192239b5a3def7

**Comment by Ingrim4** [comment]
Spawners should be hidden by default by the proximity hider but you will have too add `minecraft:player_head` in your proximity config (in the `proximity -> proximity-{overworld, nether, ...} -> hiddenBlocks` section). A proximity hidden blocks gets shown to a player once he got closer than 24 blocks and is looking roughly in the direction of the hidden block.

For more info about editing the config check out our wiki: https://github.com/Imprex-Development/Orebfuscator/wiki/Config#proximity-config-section

For more info about how the proximity hider or frustum culling work check out our FAQ: https://github.com/Imprex-Development/Orebfuscator/wiki/Frequently-Asked-Questions#what-is-the-proximity-hider

**Comment by Ingrim4** [comment]
Closed due to inactivity.
