### ISSUE TITLE
无法隐藏深层矿石

### ISSUE THREAD

**Issue by XZHStudio** [Imprex-Development/orebfuscator#352]
### Description

无法隐藏深层矿石
![image](https://github.com/Imprex-Development/orebfuscator/assets/102938713/0bfeb977-e290-489e-8a3c-9be4bf447522)

### Reproduction Steps

使用wurst打开x-ray
显示矿石

### Expected Behaviour

矿石不应该被发现

### Orebfuscator Dump

[dump-2024-02-10_07.21.18.json](https://github.com/Imprex-Development/orebfuscator/files/14228460/dump-2024-02-10_07.21.18.json)

**Comment by Ingrim4** [comment]
Looks like your config is from an older version of the game (missing deepslate ores), simply delete the config and Orebfuscator will create a new one for your current server version.

**Comment by XZHStudio** [comment]
我从1.16.5升级到1.18.2后导致了这个问题，删除配置文件后正常工作了，感谢
