### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by alexmircea27** [Imprex-Development/orebfuscator#353]
### Description

When a player its going in new chunks i get spammed in console with this

### Reproduction Steps

-

### Expected Behaviour

-
![Screenshot_20240210_110456_Chrome](https://github.com/Imprex-Development/orebfuscator/assets/7952497/1d2d2fbf-0819-4a80-8774-f2c8cb950d28)

### Orebfuscator Dump

-

**Comment by NgLoader** [comment]
Please provide an Orebfuscator dump file (use /orebfuscator dump) or if Orebfuscator didn't start provide a ProtocolLib dump (use /protocol dump). You should use https://gist.github.com/ to upload, then include the link below.

**Comment by kaweepatinn1** [comment]
same issue, here is my dump:
https://gist.github.com/kaweepatinn1/77c0cde7995dc0abd9895e4d430d785a

**Comment by Ingrim4** [comment]
Might be an issue with the cache, can you disable it and check it that solves the issue?

**Comment by kaweepatinn1** [comment]
Just saw this now, the issue seems to have not happened again since posting, and does not replicate. Will report any further issues and whether disabling cache fixes them if they occur.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
