### ISSUE TITLE
High ping issue

### ISSUE THREAD

**Issue by Leodkata** [Imprex-Development/orebfuscator#354]
### Description

Hello! I'm pretty new at all of this minecraft stuff and im using Orebfuscator, works fine but issue is some of my players get extremely high ping when they teleport anywhere - Spawn, or just tpa to another player.

Alot of people suggested that i have to change settigs in config file since im using the default ones but i honestly have no clue on what to touch there. Is it possible for someone to help me out with this? Make a less stress config version for me?
EDIT: I have disabled cache from config file but not big difference.

### Reproduction Steps

.

### Expected Behaviour

.

### Orebfuscator Dump

https://gist.github.com/Leodkata/910bf23617b1bb62f975bcea2d9df7d0

**Comment by NgLoader** [comment]
Can you try to enable inside your [config.yml](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section) the ``layerObfuscation`` settings.
This will compromise the chunk size that is sent to the player.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
