### ISSUE TITLE
Orebfuscator not creating any files

### ISSUE THREAD

**Issue by drch0ppie** [Imprex-Development/orebfuscator#355]
### Description

getting the error message 
 org.bukkit.command.CommandExceptionCannot execute command 'orebfuscator' in plugin Orebfuscator v5.4.3 - plugin is disabled.

### Reproduction Steps

Running on 1.20.4 bisect serer hosting server

### Expected Behaviour

when downloading the plugin it should create a directory and it dosent

### Orebfuscator Dump

neither commman is working

**Comment by NgLoader** [comment]
Please provide your currently server version (using the command ``/version``).
Also have you installed the latest development build from [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/)?
Are there any other console errors on startup responding to Orebfuscator?

**Comment by txversity** [comment]
I am also having this issue.

**Comment by kirito-0** [comment]
I am also having this issue.

**Comment by Ingrim4** [comment]
I would guess that all of you are using an outdated version of ProtocolLib but since no one has posted a log file or snippet I can't be sure.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
