### ISSUE TITLE
Orebfuscator not working

### ISSUE THREAD

**Issue by HuanKong-FeiNiao** [Imprex-Development/orebfuscator#357]
### Reproduction Steps

Orebfuscator not working

### Expected Behaviour

Orebfuscator not working

### Orebfuscator Dump

https://gist.github.com/HuanKong-FeiNiao/6ca2509a6d71f6e3513c42e281a21bab

**Comment by NgLoader** [comment]
Orebfuscator only listens on the default worlds.
If you're using custom worlds, you need to manually add them inside your Orebfuscator [config.yml](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#obfuscation-config-section).
Please note that you need to add your worlds inside the obfuscation and proximity hider sections.

**Comment by HuanKong-FeiNiao** [comment]
Thanks
