### ISSUE TITLE
FastAsyncWorldEdit bug

### ISSUE THREAD

**Issue by Xmonpl** [Imprex-Development/orebfuscator#36]
* Server Version: 1.16.1
* Orebfuscator Version: 5.0.0
* Protocollib Version: 4.6.0-SNAPSHOT-b473

Hello, I was able to locate such an error. The entire process is presented in the video.
https://www.youtube.com/watch?v=B9375GOsx2w
FAWE version: FastAsyncWorldEdit-1.16-312

**Comment by Ingrim4** [comment]
fixed in #37
