### ISSUE TITLE
Orebfuscator doesn´t work

### ISSUE THREAD

**Issue by TrooperIndustries** [Imprex-Development/orebfuscator#361]
### Description

I´m using mine hoster to host a server and i try to put the plugin on the server but it doesn´t work, nor get detected by the server as an actual plugin

### Reproduction Steps

I download the latest version -> Put it into the plugin folder in the server files -> It doesn´t work

### Expected Behaviour

I expected it to work

### Orebfuscator Dump

Can´t

### Extra Details

I also read through some other posts before but noone seems to be having the same issue

**Comment by NgLoader** [comment]
Please provide your currently server version (using the command ``/version``).
Also have you installed the latest development build from [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/)?
Are there any other console errors on startup responding to Orebfuscator?

**Comment by TrooperIndustries** [comment]
1. Version: [12:50:55] [Server thread/INFO]: This server is running CraftBukkit version 3871-Spigot-d2eba2c-3f9263b (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) 2. I haven´t do i need it? 3.  Its like the server doesn´t even know its in the plugins folder Edit: I think downloading ProtocolLib fixed my problem, thank you

**Comment by TrooperIndustries** [comment]
It´s fixed, didn´t know you needed the other plugin thanks
