### ISSUE TITLE
Holes and config

### ISSUE THREAD

**Issue by Y4NN1Z** [Imprex-Development/orebfuscator#363]
### Description

I can see big holes of air and the config is a bit tricky and can't hide secret base blocks like furnaces and stuff

### Reproduction Steps

![2024-03-18_12 24 00](https://github.com/Imprex-Development/orebfuscator/assets/163844262/30f1c259-6ae1-42e4-b5fd-7a43afb019eb)
![2024-03-18_12 23 45](https://github.com/Imprex-Development/orebfuscator/assets/163844262/d0446a82-7e8e-4719-acb8-58d85cfcb3e3)

### Expected Behaviour

I need to see full and not those holes those holes can expose secret bases and stuff and also can i get a tutorial on how to hide all blocks i mean enchanting table, brewing stand, bookshelf and all those other blocks?

### Orebfuscator Dump

does not work, it's unavailable site.

### Extra Details

please guys help me fix this it's annoying and i want to have it good !

**Comment by NgLoader** [comment]
Please upload you orebfuscator dump somewhere where we can access it.
Like: [Pastenbin](https://pastebin.com/), [Github Gist](https://gist.github.com/) or somewhere else.

Without that were unable to provide any kind of support.
Or you need to provide some more details like version details world names and config changes.

**Comment by Ingrim4** [comment]
Closed due to inactivity.
