### ISSUE TITLE
Minecraft 1.21

### ISSUE THREAD

**Issue by john22211** [Imprex-Development/orebfuscator#376]
### Description

Good morning, when will orebfuscator support version 1.21?

### Reproduction Steps

support version 1.21

### Expected Behaviour

fix the error as quickly as possible

### Orebfuscator Dump

i don't have :(

**Comment by Ingrim4** [comment]
You can try the early dev build here: https://github.com/Imprex-Development/orebfuscator/actions/runs/9528215040/artifacts/1604772033 (but no guarantees that everything will work)
