### ISSUE TITLE
On 1.16.1 Commands dont work

### ISSUE THREAD

**Issue by ColdtQ** [Imprex-Development/orebfuscator#38]
**Please fill out the following information:**
* Server Version: 1.16.1
* Orebfuscator Version: 5.0.0
* Protocollib Version: Latest dev build.

**Describe the bug**
Describe the bug clearly and how to produce it

Join a 1.16.1 server with Orebfuscator and ProtocolLib installed and try to run any commands /ofc. They don't work.

**Comment by Ingrim4** [comment]
This is intended since there are currently no commands implemented.
