### ISSUE TITLE
Incompatibility with Veinminer plugin

### ISSUE THREAD

**Issue by Clyde6790pGIT** [Imprex-Development/orebfuscator#384]
### Description

When paired with plugin Veinminer plugin or datapack version (https://modrinth.com/datapack/veinminer) and a player that is not xraying finds a vein and veinminer automines the whole vein, they will see a bunch of fake ores ment to be visible only to xrayers.
![image](https://github.com/user-attachments/assets/72690492-5173-400a-9d82-4fa77813341d)

### Reproduction Steps

1. Use orebfuscator alongside Veinminer
2. Find an ore vein
3. A bunch of fake ores appear

### Expected Behaviour

Orebfuscator should automatically update the fake ores and show the real blocks when Veinminer breaks it.

### Orebfuscator Dump

[dump-2024-07-20_11.55.55.json](https://github.com/user-attachments/files/16320000/dump-2024-07-20_11.55.55.json)

### Extra Details

You may be able to solve this by hooking into Veinminer, but I'm not sure how to hook into it.

**Comment by Ingrim4** [comment]
Impossible to fix since we can't hook into the servers code like a mod with mixins could.
