### ISSUE TITLE
Orebfuscator not working

### ISSUE THREAD

**Issue by Donld2** [Imprex-Development/orebfuscator#385]
### Description

It says that the plugin and protocol lib are also disabled how do I enable it

### Reproduction Steps

Added it to my plugin list and it isnt working using 5.20 protocol lib

### Expected Behaviour

it to work

### Orebfuscator Dump

none of the plugins are working so I cant get the dump

**Comment by NgLoader** [comment]
Can you please provide some more information like your currently server version (``/version``).

**Comment by Ingrim4** [comment]
Closed due to inactivity
