### ISSUE TITLE
Как сделать 

### ISSUE THREAD

**Issue by Artemon-prog** [Imprex-Development/orebfuscator#388]
### Description

Как сделать чтобы только игроки с иксрыем могли видет заменёные блоки а не все игроки ?
(How to make it so that only players with xray can see the replaced blocks and not all players ?)

### Reproduction Steps

П

### Expected Behaviour

П

### Orebfuscator Dump

П

### Extra Details

Н

**Comment by Ingrim4** [comment]
What do you mean by "can see the replaced blocks". What is a replaced block can you maybe give an example or screenshot? Are you talking about obfuscated blocks that got visible?

**Comment by Ingrim4** [comment]
Closed due to inactivity
