### ISSUE TITLE
Blocks are not updated in the radius after breaking

### ISSUE THREAD

**Issue by makksgam** [Imprex-Development/orebfuscator#390]
### Description

Good afternoon, I immediately apologize for the English, I am writing through a translator.

I have a problem that after breaking the blocks, they are not updated from the point of breaking the block as they should according to the documentation. After all, there is a setting in the config 
updateOnBlockDamage: true
and updateRadius: 10 (default: 2)

But in fact, when the blocks are broken, they are updated when moving or when the camera is rotated. Maybe I'm doing something wrong, I'll attach it to this video below.

https://youtu.be/VhGZefSW8aM (0:08)

UPD: In the video, I dig with a custom pickaxe 3 by 3, but this problem persists even if I dig with a regular pickaxe

### Reproduction Steps

-

### Expected Behaviour

-

### Orebfuscator Dump

-

### Extra Details

https://youtu.be/VhGZefSW8aM (0:08)

**Comment by Ingrim4** [comment]
Thank you for bringing this issue to our attention. Unfortunately, the problem you're encountering is a known limitation that we currently cannot resolve. When a plugin sends block updates, other plugins, like Orebfuscator, do not receive notifications about these changes.

The only way to address this behavior is for the plugin in question to interact with our API, providing a list of updated blocks. This allows us to properly deobfuscate any neighboring blocks that may have been affected.

To help you, we've provided a [simple example](https://github.com/Imprex-Development/orebfuscator/blob/d6ba5bf0537345c306ab4161e1829d9fa835341f/orebfuscator-api-example/src/main/java/net/imprex/api/example/Example.java#L49) of a plugin that adds a pickaxe capable of breaking multiple blocks simultaneously, which demonstrates the concept you're dealing with.
