### ISSUE TITLE
Wrong ProtocoLib version?

### ISSUE THREAD

**Issue by Jtcoop** [Imprex-Development/orebfuscator#40]
* Server Version: 1.16.2
* Orebfuscator Version: 5.0.0
* ProtocolLib Version: 4.6.0-SNAPSHOT

I'm not sure if this belongs here but the plugin does not work currently and I am wondering if there is another version of ProtocolLib that I should be using or if there is something else I should be doing. I got the plugin to work great on 1.15.2 but I have not been able to get it working for 1.16.2.

**Comment by Ingrim4** [comment]
I can't reproduce this problem. Did the console output any exceptions?

**Comment by Jtcoop** [comment]
I got it to work by changing the name of the world in the config. I saw in another one of your comments that there are not supposed to be in-game commands for this version of orebfuscator. Is that correct?

**Comment by Ingrim4** [comment]
See: https://github.com/Imprex-Development/Orebfuscator/issues/35#issuecomment-674458263 

`Commands are planned but currently not implemented.`
