### ISSUE TITLE
WHERE IS THE CONFIG

### ISSUE THREAD

**Issue by SuperSurferNow** [Imprex-Development/orebfuscator#404]
### Description

I'M SORRY THIS IS NOT THE ISSUE BUT YOU DONT SAY ANYWHERE WHERE IS THE CONFIG FOR THE MOD PLEASE HELP ME I'VE BEEN SEARCHING FOR AGES

### Reproduction Steps

1. TELL ME WHERE IT IS
2. I'LL BE CALM

### Expected Behaviour

WHAT

### Orebfuscator Dump

NO

**Comment by NgLoader** [comment]
This project relies on mutual respect and constructive communication. Unfortunately, this issue does not meet those standards. Please consider revising your tone and providing clear, actionable details if you wish to reopen or create a new issue in the future.
