### ISSUE TITLE
FPS lag

### ISSUE THREAD

**Issue by Xaldrosis** [Imprex-Development/orebfuscator#44]
I've installed this addon and everyone is experiencing FPS lag. FPS is reduced by over half.
After removing the addon the lag remains...

**Comment by Ingrim4** [comment]
See #35

**Comment by Xaldeon** [comment]
I have turned off air blocks, it improved the fps slightly. You start off at normal fps and then it tanks down. One user even went down from 98 fps to 17 fps.
