### ISSUE TITLE
Replaced nodes still apearing to players while mining

### ISSUE THREAD

**Issue by Xaldrosis** [Imprex-Development/orebfuscator#45]
**Please fill out the following information:**
* Server Version: 1.16.2 spigot
* Orebfuscator Version: 5.0.0
* Protocollib Version: 4.5.1

**Describe the bug**
Describe the bug clearly and how to produce it

Players are mining and they will sometimes see the replaced nodes.

[Screenshot 1](http://prntscr.com/unbte5)
[Screenshot 2](http://prntscr.com/unbuz6)

After hitting it once the surrounding nodes turn normal again.

[Screenshot 3](http://prntscr.com/unbw2k)

**Comment by NgLoader** [comment]
Can't reproduce the bug, can you please give us more information?

**Comment by Xaldrosis** [comment]
It's really hard to reproduce this. It doesn't happen often, but I've had players tell me they see this like once or twice a day.

They randomly find these spots while running around and adventuring. The position from the screenshots was at the surface like 5 blocks deep.

EDIT: I've had another report of user telling me that chests in caves sometimes appears as regular blocks and they need to hit them first for it to turn back into a chest.

**Comment by Xaldrosis** [comment]
Here's the default config, I've only removed the airblocks so far.

version: 1
general:
  updateOnBlockDamage: true
  bypassNotification: true
  initialRadius: 1
  updateRadius: 2
  proximityHiderRunnerSize: 4
cache:
  enabled: true
  baseDirectory: 'orebfuscator_cache/'
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000‬
  maximumSize: 4096
  expireAfterAccess: 30000
world:
  - worlds:
      - world
    enabled: true
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - spawner
      - emerald_ore
      - diamond_ore
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - redstone_ore
      - stone
      - clay
      - shulker_box
      - white_shulker_box
      - orange_shulker_box
      - magenta_shulker_box
      - light_blue_shulker_box
      - yellow_shulker_box
      - lime_shulker_box
      - pink_shulker_box
      - gray_shulker_box
      - light_gray_shulker_box
      - cyan_shulker_box
      - purple_shulker_box
      - blue_shulker_box
      - brown_shulker_box
      - green_shulker_box
      - red_shulker_box
      - black_shulker_box
    randomBlocks:
      clay: 1
      coal_ore: 1
      cobblestone: 1
      diamond_ore: 25
      emerald_ore: 10
      gold_ore: 5
      iron_ore: 5
      lapis_ore: 1
      mossy_cobblestone: 1
      obsidian: 1
      redstone_ore: 1
      stone: 1
      tnt: 1
  - worlds:
      - world_nether
    enabled: true
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - spawner
      - netherrack
      - nether_quartz_ore
      - shulker_box
      - white_shulker_box
      - orange_shulker_box
      - magenta_shulker_box
      - light_blue_shulker_box
      - yellow_shulker_box
      - lime_shulker_box
      - pink_shulker_box
      - gray_shulker_box
      - light_gray_shulker_box
      - cyan_shulker_box
      - purple_shulker_box
      - blue_shulker_box
      - brown_shulker_box
      - green_shulker_box
      - red_shulker_box
      - black_shulker_box
      - ancient_debris
      - nether_gold_ore
      - basalt
      - soul_sand
      - soul_soil
    randomBlocks:
      netherrack: 4
      nether_quartz_ore: 1
      nether_gold_ore: 1
      ancient_debris: 1
  - worlds:
      - world_the_end
    enabled: true
    hiddenBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - spawner
      - shulker_box
      - white_shulker_box
      - orange_shulker_box
      - magenta_shulker_box
      - light_blue_shulker_box
      - yellow_shulker_box
      - lime_shulker_box
      - pink_shulker_box
      - gray_shulker_box
      - light_gray_shulker_box
      - cyan_shulker_box
      - purple_shulker_box
      - blue_shulker_box
      - brown_shulker_box
      - green_shulker_box
      - red_shulker_box
      - black_shulker_box
    randomBlocks:
      end_stone: 1
      end_stone_bricks: 1
      bedrock: 1
      obsidian: 1
      purpur_block: 1

proximity:
  - worlds:
      - world
    enabled: true
    distance: 16
    useFastGazeCheck: false
    hiddenBlocks:
      diamond_ore: {}
      emerald_ore: {}
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      blast_furnace: {}
      cartography_table: {}
      fletching_table: {}
      grindstone: {}
      composter: {}
      lectern: {}
      loom: {}
      smithing_table: {}
      smoker: {}
      stonecutter: {}
      hopper: {}
      spawner: {}
      shulker_box: {}
      white_shulker_box: {}
      orange_shulker_box: {}
      magenta_shulker_box: {}
      light_blue_shulker_box: {}
      yellow_shulker_box: {}
      lime_shulker_box: {}
      pink_shulker_box: {}
      gray_shulker_box: {}
      light_gray_shulker_box: {}
      cyan_shulker_box: {}
      purple_shulker_box: {}
      blue_shulker_box: {}
      brown_shulker_box: {}
      green_shulker_box: {}
      red_shulker_box: {}
      black_shulker_box: {}
      bee_nest: {}
      beehive: {}
    randomBlocks:
      stone: 1
  - worlds:
      - world_nether
    enabled: true
    distance: 16
    useFastGazeCheck: false
    hiddenBlocks:
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      blast_furnace: {}
      cartography_table: {}
      fletching_table: {}
      grindstone: {}
      composter: {}
      lectern: {}
      loom: {}
      smithing_table: {}
      smoker: {}
      stonecutter: {}
      hopper: {}
      spawner: {}
      shulker_box: {}
      white_shulker_box: {}
      orange_shulker_box: {}
      magenta_shulker_box: {}
      light_blue_shulker_box: {}
      yellow_shulker_box: {}
      lime_shulker_box: {}
      pink_shulker_box: {}
      gray_shulker_box: {}
      light_gray_shulker_box: {}
      cyan_shulker_box: {}
      purple_shulker_box: {}
      blue_shulker_box: {}
      brown_shulker_box: {}
      green_shulker_box: {}
      red_shulker_box: {}
      black_shulker_box: {}
      bee_nest: {}
      beehive: {}
      ancient_debris: {}
      nether_gold_ore: {}
      respawn_anchor: {}
    randomBlocks:
      netherrack: 4
      nether_quartz_ore: 1
      nether_gold_ore: 1
      ancient_debris: 1
  - worlds:
      - world_the_end
    enabled: true
    distance: 16
    useFastGazeCheck: false
    hiddenBlocks:
      chest: {}
      ender_chest: {}
      trapped_chest: {}
      anvil: {}
      crafting_table: {}
      dispenser: {}
      enchanting_table: {}
      furnace: {}
      blast_furnace: {}
      cartography_table: {}
      fletching_table: {}
      grindstone: {}
      composter: {}
      lectern: {}
      loom: {}
      smithing_table: {}
      smoker: {}
      stonecutter: {}
      hopper: {}
      spawner: {}
      shulker_box: {}
      white_shulker_box: {}
      orange_shulker_box: {}
      magenta_shulker_box: {}
      light_blue_shulker_box: {}
      yellow_shulker_box: {}
      lime_shulker_box: {}
      pink_shulker_box: {}
      gray_shulker_box: {}
      light_gray_shulker_box: {}
      cyan_shulker_box: {}
      purple_shulker_box: {}
      blue_shulker_box: {}
      brown_shulker_box: {}
      green_shulker_box: {}
      red_shulker_box: {}
      black_shulker_box: {}
      bee_nest: {}
      beehive: {}
    randomBlocks:
      end_stone: 1

**Comment by Ingrim4** [comment]
Any other plugins on your server that could cause thoose problems?

**Comment by Xaldrosis** [comment]
We run 4 other mods. AdminGUI-1.4.5, CustomTime-2.0, SuperVanish-6.2.0 and Logblock-1.16.1.1

Logblock shouldn't be an issue as that's been added after your addon and the issues were already there. The other 3 mods were there before we added yours.

**Comment by SydMontague** [comment]
The error seems to appear quite often at chunk borders, potentially even chunk region borders.

**Comment by Xaldrosis** [comment]
A user disconnected and came back like an hour later. He was mining in tunnels before he logged off and when he logged back in he saw fake diamonds on a wall next to him.

**Comment by Xaldrosis** [comment]
Someone logged on and all their chests were cobble in their base.

[Screenshot](https://cdn.discordapp.com/attachments/753340410968932362/759927466130931722/unknown.png)

**Comment by NgLoader** [comment]
Can you please try it again with latest version?

**Comment by Xaldrosis** [comment]
I'll install it and ask the users for feedback.

Edit: Installed it and noticed this minor thing in console :)

[22:08:11] [Server thread/INFO]: [Orebfuscator] Enabling Orebfuscator **v5.0.0**

**Comment by Ingrim4** [comment]
ups didn't change the version in plugin.yml xD

**Comment by Krater107a** [comment]
Could also be having a very similar problem on a small server I host.

[https://i.postimg.cc/N0KgQVVR/2020-10-14-22-50-12.png](url)

The stone blocks you are seeing in the pic, should be some shulkers and chests, yet they remain obscured.

**Comment by Xaldrosis** [comment]
Someone just reported seeing fake ores

**Comment by Ingrim4** [comment]
Do you know when this happened? (after login, mining or something else)

**Comment by Krater107a** [comment]
This is observed happening to players right after they log in or if they came through a nether / end portal.

**Comment by Ingrim4** [comment]
@Krater107a could you please open a new issue for your problem since it has something to do with the proximity hider not the obfuscation.

**Comment by Xaldrosis** [comment]
> 
> 
> Do you know when this happened? (after login, mining or something else)

Randomly when mining / adventuring

**Comment by Ingrim4** [comment]
> Randomly when mining / adventuring

Maybe I should have made myself more clear. What I meant was does this happen after some blocks got destroyed by whatever means (block break, ...) or do these sometimes appere at the surface of the world (cave, ...). Because when these appere just randomly at the surface without players interference that would mean the obfuscation is at fault otherwise the update listener.

**Comment by Krater107a** [comment]
From the best I understand; that picture shows one of my players, a moment or two after he had logged in. Those stone blocks on the floor should be both some single block chest as well as a shulker or two. (if he were farther away then this would be no problem, but he's pretty close to em) but they are still 'stone' even though he is close to them.... Note: this problem seems to only be happening on the latest update to orebfuscator (5.1.0). I rolled back orebfuscator to (5.0.0) for the last 3 days and haven't heard any more complaints from my players. -- Please note: this is a superb plugin that literally saved my server. (anarchy server but with some anticheat) people couldn't hide anything because of stupid chest esp but this plugin stops that... well done 👍

**Comment by Ingrim4** [comment]
Have possibly found the cause of this problem will probably fix it in the next update.
