### ISSUE TITLE
Barrels are visible

### ISSUE THREAD

**Issue by MoonCrowned** [Imprex-Development/orebfuscator#49]
* Server Version: papermc_387
* Orebfuscator Version: 5.0.0
* Protocollib Version: v4.5.1

Barrels are visible, if added in config.yml as
- barrel
They are simple containers + cool decor, so players often use them in their bases. But they are visible, so griefing is simple. I think it is easy to fix it, just add to some entities list to hide.

**Comment by Ingrim4** [comment]
Could you please upload/post your config?

**Comment by Ingrim4** [comment]
Closed due to inactivity
