### ISSUE TITLE
Can't receive chunks

### ISSUE THREAD

**Issue by molor** [Imprex-Development/orebfuscator#60]
**Please fill out the following information**
* Server Version: Paper 1.16.3
* Orebfuscator Version: Below
* Protocollib Version: Below

**Describe the bug**
I'm just fastly reconnected to the server 1-2 times and chunks won't received even after two minutes of waiting..

![2020-10-25_13 31 41](https://user-images.githubusercontent.com/19989717/97104637-82e03700-16c6-11eb-8636-9a26c80be374.png)

Then I type **stop** command in server console because there was nothing else I could do :/

```
[2020-10-25 13:26:59 | Server thread] [ProtocolLib] Disabling ProtocolLib v4.6.0-SNAPSHOT-b480
[2020-10-25 13:26:58 | Server thread] [Orebfuscator] Disabling Orebfuscator v5.1.1
[2020-10-25 13:26:59 | ofc-chunk-serializer] Exception in thread "ofc-chunk-serializer" java.lang.NullPointerException
[2020-10-25 13:26:59 | ofc-chunk-serializer] 	at net.imprex.orebfuscator.cache.AsyncChunkSerializer.run(AsyncChunkSerializer.java:95)
[2020-10-25 13:26:59 | ofc-chunk-serializer] 	at java.lang.Thread.run(Unknown Source)
```

**Comment by Ingrim4** [comment]
Did this just happen this one time or is it a recurring thing? Where there any other exceptions, did you modify the config, is this a normal world, any other plugins that could interfere?

**Comment by Ingrim4** [comment]
Should this ever recur please send us a screenshot of your F3 debug screen like below.
![debug screen](https://user-images.githubusercontent.com/8127996/97108051-20d60080-16cb-11eb-8011-5c37bbc26c1e.png)

**Comment by molor** [comment]
> recurring thing

This is.
> Where there any other exceptions

None.
> did you modify the config

https://pastebin.com/680QKbEv
> this a normal world

Yes, sometimes nether have same issue.

> please send us a screenshot of your F3 debug screen

@Ingrim4, just now:

![image](https://user-images.githubusercontent.com/19989717/97114985-e8531880-1704-11eb-99d8-bd4767f3f347.png)

**Comment by Ingrim4** [comment]
Does deleting the cache (when the server isn't running) fix the issue? Does your cache folder have write permissions?

**Comment by molor** [comment]
> Does deleting the cache (when the server isn't running) fix the issue?

No :c 

Steps that I do: removed cache folder, started server, joined the game (in Creative mode while flying above ground, so I can't move until chunks received by client), disconnected, quickly repeat last 2 steps 2-4 times in a row and got "Waiting for chunk...". CPU isn't overloaded (~30%), RAM use 20%.

> Does your cache folder have write permissions?

Of course. By the way, regarding cache folder, please return back the ability to move it outside of the server "worlds" folder. Previously (Orebfuscator4) I could move it to RAM-disk, but now I can't.

**Comment by Ingrim4** [comment]
> Steps that I do: removed cache folder, started server, joined the game (in Creative mode while flying above ground, so I can't move until chunks received by client), disconnected, quickly repeat last 2 steps 2-4 times in a row and got "Waiting for chunk...". CPU isn't overloaded (~30%), RAM use 20%.

Since I can't reproduce this, I've written a hackish debug version that I would like you to use. Should the bug occur just type `/debug` to open a debug inventory and send use the data in it.
[link expired](https://drive.google.com)

> Of course. By the way, regarding cache folder, please return back the ability to move it outside of the server "worlds" folder. Previously (Orebfuscator4) I could move it to RAM-disk, but now I can't.

Will add this in the next version. (could maybe try to use symlink till then)

**Comment by molor** [comment]
@Ingrim4,

![image](https://user-images.githubusercontent.com/19989717/97353819-91387980-18a5-11eb-81b4-4f7f4f9e4728.png)
![image](https://user-images.githubusercontent.com/19989717/97353836-95fd2d80-18a5-11eb-8e6b-6238ce37763c.png)
![image](https://user-images.githubusercontent.com/19989717/97353849-9ac1e180-18a5-11eb-81ce-ec1d165443c8.png)

**Comment by molor** [comment]
I also has a `orebfuscator.bypass` permission, if it's important

**Comment by Ingrim4** [comment]
The `orebfuscator.bypass` permission changes everything this looks like a client problem since we don't even touch packets of bypassed players. Maybe optifine will fix it for you. If other players should expirience the same problem then it's probably a problem with ofc.

**Comment by NgLoader** [comment]
Have you ever tested it without OFC?

**Comment by molor** [comment]
> Have you ever tested it without OFC?

Sure, and everything is working fine every time

**Comment by NgLoader** [comment]
Have you any other plugins on your server?

**Comment by Ingrim4** [comment]
If you disable the cache does that maybe fix the issue?

**Comment by molor** [comment]
When I noticed this problem, I started deleting plugins one by one in order to find the causer. Stopped at OFC, without it everything is good.

In addition, if I stop the server with the `stop` command while the client is "waiting for chunks" — before disconnecting from the server, but after disabling OFC, chunks are immediately loaded. So it's not a client issue

**Comment by molor** [comment]
> If you disable the cache does that maybe fix the issue?

Hmm, without cache everything is works fine and all chunks loads instantly after connection.. Thanks, this will work as a temporary solution. But I would still like to understand what this problem is and fix it completely.

**Comment by Ingrim4** [comment]
Probably something with ProtocolLib not sending packets when you simply return. (Maybe it's the new ProtocolLib version that causes this issue since I used 4.5.0 for testing)

**Comment by Ingrim4** [comment]
I've now tested your setup with ProtocolLib v4.6.0-b480 and Paper b240. Sometimes the chunks next to the player don't load maybe this is paper thing but it's not as bad as what you're expiriencing.

**Comment by molor** [comment]
I will try ProtocolLib 4.5 tomorrow and tell if something has changed

**Comment by molor** [comment]
Nothing changed with PL 4.5

**Comment by Ingrim4** [comment]
and does it work without paper cause that's what i suspect

**Comment by molor** [comment]
> and does it work without paper cause that's what i suspect

On Spigot it works fine with enabled cache..

**Comment by Ingrim4** [comment]
Then I'm sorry to say that we currently only maintain spigot support but we do have plans to support forks of it at a later time. There are a few things you can still try, update Paper and ProtocolLib to the latest dev builds or use our [latest dev build](https://github.com/Imprex-Development/Orebfuscator/actions).

**Comment by molor** [comment]
I can't stop using Paper, as it will loads at least twice as fast as Spigot, allows me to configure a lot of things I need, and almost all other plugins (even WorldEdit!) recommends it. But I understood you, for now I disable cache and will wait for full support.. Thanks.

**Comment by Ingrim4** [comment]
Could you maybe check if the new 5.1.3 release fixed this issue since I can't reproduce it.

**Comment by molor** [comment]
Can't check this because now I'm using Paper built-in Anti X-Ray and only use Orebfuscator because of Proximity Hider.
You can close this issue if you want to.

**Comment by Pianist20005** [comment]
Hello, I want to inform you that I have/had the same problem:
Server: Spigot 1.16.4 (with a bungeecord network)
Plugins: ProtocolLib 4.5.1, Orebfuscator 5.1.3, Luckperms + Luckpermchat, Varo

If I join from my main server to the server where ofc is installed, then some mobs are visible as molo already send pictures, but the chunks don't load. (I waited for half an hour, but nothing changed, -> Players cannot move and mobs are bugging around). After I switch to my main server an rejoin the server with ofc, then it is working without any issues. (sometimes I have to rejoin twice.) I use the normal Minecraft-Launcher no modification or something like that. (This problem also appears also in the whole server team an other players)

-> After I disabled the cache everything works fine. Is it possible that it may lag a little more without the cache?

One more question: When I am on the server with the standard resourcepack it does not lag. But if I activate a x-ray pack it is really laggy -> Is this from the server or from the client?

Thanks for helping and answering!

**Comment by Ingrim4** [comment]
> Hello, I want to inform you that I have/had the same problem:

I'm sorry to say that I can't fix the issue without the ability to reproduce it.

> -> After I disabled the cache everything works fine. Is it possible that it may lag a little more without the cache?

Yes most definitely but it depends on the amount of players.

> One more question: When I am on the server with the standard resourcepack it does not lag. But if I activate a x-ray pack it is really laggy -> Is this from the server or from the client?

Should be client lag since the renderer can't handle all the air blocks.

**Comment by Pianist20005** [comment]
Thanks for the information! 

I can show it to you on my server, or you can try it on your own, but I don't want to poste my serveradress in here, because my server is not finished yet. Is there an other way how I can give/send it to you? Then you can try out, and probably you find the issue.

Okay but it should not be a big deal for the server: There are 16GB Ram for a maximum of 30 players. 

Okay that's very good!

**Comment by Ingrim4** [comment]
Just add me on discord: Maurice#7519

**Comment by kyle-vasilia** [comment]
I am having this issue aswell on the latest version on a 1.16.4 server - it worked fine for nearly a month until this point - emptying cache did nothing, I'll disable it for now

**Comment by Ingrim4** [comment]
Are you using the latest version of ProtocolLib? https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by pintoso** [comment]
Its fixed for me using latest ProtocolLib version.

**Comment by TimurYP** [comment]
Hi, I'm having difficulty, how to disable obfuscation for OP players on version 1.16.4?

**Comment by CombatMedic02** [comment]
Hello, I wanted to say that after updating to the new version of this plugin I am also having the chunks not loading problem. Until I relog nothing loads. Before updating to this version when I teleported occasionally chunks would stop loading until I relogged. 

My ProtocolLib is Dev Build #540 and I'm running Paper-1.18.1-117.

What do I need to do to fix this issue?

**Comment by paperna** [comment]
So this problem is solved by disabling the Orebusacator cache?

**Comment by Ingrim4** [comment]
Probably not, this is still something I have not idea of how to fix it.

**Comment by Ingrim4** [comment]
Could you try if this fixed it for you: https://github.com/Imprex-Development/Orebfuscator/suites/4878107752/artifacts/139481868 (source: https://github.com/Imprex-Development/Orebfuscator/tree/test-fix-for-chunk-not-loading)
