### ISSUE TITLE
hiddenBlocks and randomBlocks written in inconsistent order

### ISSUE THREAD

**Issue by Bobcat00** [Imprex-Development/orebfuscator#61]
**Please fill out the following information:**
* Server Version: git-Spigot-57bbdd8-55a78ff (MC: 1.16.3)
* Orebfuscator Version: 5.1.1
* Protocollib Version: 4.6.0-SNAPSHOT-b482

**Describe the bug**
In the default config.yml file created by the plugin, hiddenBlocks and randomBlocks are in an arbitrary order. This makes it difficult for server owners to compare config files to see what has changed when a new version is released.

I think if you use LinkedHashSet and LinkedHashMap, the config file entries will be written in a consistent order:

orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/config/OrebfuscatorWorldConfig.java

From `private final Set<Material> hiddenBlocks = new HashSet<>();`
To `private final Set<Material> hiddenBlocks = new LinkedHashSet<>();`

From `private final Map<Material, Integer> randomBlocks = new HashMap<>();`
To `private final Map<Material, Integer> randomBlocks = new LinkedHashMap<>();`

I'm unable to get Eclipse to build your plugin, so I could not test this myself.

I suppose there might be other ways to sort hiddenBlocks and randomBlocks. Anything to keep the order consistent between releases would help.

**Comment by Ingrim4** [comment]
Seems like a good idea. Maybe we should even use the default minecraft order. Will implement this in the next bigger update which will enhance the config anyway.
