### ISSUE TITLE
May you help me?

### ISSUE THREAD

**Issue by Ofek270704** [Imprex-Development/orebfuscator#63]
The plugin doesn't work for me. I am on Minecraft version 1.16.3 and running the plugin version 5.1.1

**Comment by NgLoader** [comment]
Can you please provide some more informations?
Server version?
Protocollib version?

any console errors?

**Comment by Ofek270704** [comment]
server version is 1.16.3 
protocollib version is 4.5.1

**Comment by NgLoader** [comment]
Are you using spigot?
**Any console errors?**

**Comment by Ofek270704** [comment]
no errors

**Comment by Ofek270704** [comment]
I just checked now.

**Comment by Ofek270704** [comment]
and it still doesn't work

**Comment by Ofek270704** [comment]
[Orebfuscator] Enabling Orebfuscator v5.1.1
[Orebfuscator] cache.protocolLibThreads is less than one, choosing processor count as value = 16
[Orebfuscator] Searching NMS protocol for server version "v1_16_R2"!
[Orebfuscator] NMS protocol for server version "v1_16_R2" found!

**Comment by Ofek270704** [comment]
it is not an error

**Comment by NgLoader** [comment]
Have you * permissions?

**Comment by Ofek270704** [comment]
what permissions?

**Comment by Ofek270704** [comment]
I have luckperms on my server

**Comment by NgLoader** [comment]
Yea, ofc is working on you server but when you have **'*'** or **orebfuscator.bypass** permissions the plugin don't obfuscate your chunks only for players without permissions

**Comment by Ofek270704** [comment]
yea the players without perms and it does not obfuscate the chunks.

**Comment by NgLoader** [comment]
Have you any other plugins on you server?

**Comment by Ofek270704** [comment]
wait I will send you the plugins

**Comment by Ofek270704** [comment]
![image](https://user-images.githubusercontent.com/67981835/97542760-f7b9b680-19cf-11eb-89cc-9ad06adb499a.png)

**Comment by NgLoader** [comment]
Can you please try to run only Orebfuscator and ProtocolLib and when it works to enable the other plugins one by one?
Ps: you can rename the .jar to like .jarr and it will not be loaded as a plugin.

**Comment by Ofek270704** [comment]
ok

**Comment by Ofek270704** [comment]
still not work

**Comment by Ofek270704** [comment]
I will send you the config of the oreb plugin

**Comment by Ofek270704** [comment]
I need to change the config my world name is survival. I changed the config and its return to the old config.

**Comment by NgLoader** [comment]
You can only edit the config when the server is stopped

**Comment by Ofek270704** [comment]
I found the bug now its work

**Comment by Ofek270704** [comment]
I change the name of the world

**Comment by Ofek270704** [comment]
I change the name to world

**Comment by NgLoader** [comment]
Okay 😄
