### ISSUE TITLE
Unable to locate sign message in chat

### ISSUE THREAD

**Issue by AMDBartek** [Imprex-Development/orebfuscator#80]
**Please fill out the following information:**

* Server Version: 
git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
* Orebfuscator Version: 
Orebfuscator version 5.1.2
* Protocollib Version: 
ProtocolLib version 4.5.1

**Describe the bug**
When joining the server on a 1.8.x client with ViaBackwards + ViaRewind (or any backwards compatibility plugin) there is an Unable to locate sign message in chat. I have the orebfuscator.bypass permission.

If you require more information please do not hesitate to ask.

This does NOT happen without Orebfuscator installed.

Screenshot: https://i.imgur.com/lRcJRtp.png

**Comment by Ingrim4** [comment]
This problem is related to the clientbound UpdateSignPacket which got removed in 1.9 and later version. Since we only support 1.9.4+ we won't fix this issue since this will only ever happen to 1.8 and below clients.
