### ISSUE TITLE
Plugin Disconnecting Players, Seemingly Related to Quantity (Not Identity) Of Other Installed Plugins

### ISSUE THREAD

**Issue by duckysarts** [Imprex-Development/orebfuscator#81]
**Please fill out the following information:**

* Server Version: Paper-310-1.16.4
* Orebfuscator Version: orebfuscator-plugin-5.1.3
* Protocollib Version: 4.5.1

**Describe the bug**

Upon installing Orebfuscator and running the server (with other plugins installed as well), players can no longer reach the server in the server list (not even I can reach it as the host, via 'localhost'.) If I attempt to connect to the server anyway, the console prints this error as it disconnects the player:
"
Masterductape lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalAccessError: tried to access field com.comphenix.protocol.events.PacketEvent.networkMarker from class com.comphenix.protocol.events.NetworkMarker
"

somewhat insanely, it seems like Orebfuscator's weird behavior is unrelated to which plugins are installed, only how many. I started going through and systematically removing plugins to try and see which was incompatible with Orebfuscator and it seems like as long as I only have ~47 installed, it works fine. (But then MMOItems crashes. Also seemingly related to # of plugins installed being too few. I know this sounds crazy and I am thoroughly confused.) I have taken out and readded different combinations of plugins and it doesnt seem to matter which plugins are installed, only how many. If more than ~47 are installed, and Orebfuscator is installed, players cannot reach or connect to the server. It runs fine without orebfuscator installed.

And sometimes MMOItems crashes when there are too few plugins installed, again seemingly unrelated to which plugins, only how many.  So idek what the heck is happeninggggg >.<

**Comment by duckysarts** [comment]
Update:
The above is still true. 

Everything works fine on my ~59 plugins server, until I add Orebfuscator. Adding Orebfuscator causes every plugin with a ProtocolLib dependency to break, basically. I am running the latest version of Paper, but the behavior is the same on spigot in the testing that I did.

**Comment by Ingrim4** [comment]
First of all your ProtocolLib version isn't compatible with 1.16 and above, for newer versions check this: https://ci.dmulloy2.net/job/ProtocolLib/
You could also try disabling the cache inside the config and see if that helps since it uses the async api of ProtocolLib which might cause some problems. But other than that I don't know what could cause that problem.

**Comment by duckysarts** [comment]
Hello :)

When I run on ProtocolLib's latest dev builds, it does indeed work fine until I add Orebfuscator, at which point ProtocolLib crashes and none of the plugins with it as a dependency will launch. Because of the error thrown by ProtocolLib when I add Orebfuscator, I also submitted a ticket on their GitHub: https://github.com/dmulloy2/ProtocolLib/issues/1030

Disabling the cache feature (cache -> enabled: false) does not seem to make a difference. 

It would be epic if we could figure this out because Orebfuscator is the best anti-xray out there so please let me know if I can provide any additional information in the interest of troubleshooting.

**Comment by duckysarts** [comment]
I am on Java 12 by the way, if that is relevant. I've also updated to paper-1.16.4-313.
.

**Comment by Ingrim4** [comment]
Technically Java is for the most part backwards compatible but you could still try if using Java 8 changes anything. Would also guess that if Orebfuscator is the reason for the crash that it's probably incompatible with one or more plugins below:
```
Plugins Using ProtocolLib:
LibsDisguises by [libraryaddict, Byteflux, Navid K.]
PremiumVanish by [MyzelYam]
MythicMobs by [Ashijin]
LibHatesMods by [libraryaddict]
CombatLogX by [SirBlobman]
ItemsAdder by [LoneDev, LoneDev]
```

**Comment by duckysarts** [comment]
I was on Java 8 before my recent update to Java 12 and was still having issues. 

When I run a server with each of those^ & ProtocolLib installed, (but nothing else installed), everything launches/runs fine:
![image](https://user-images.githubusercontent.com/75456352/101551827-f1274300-396e-11eb-888f-c7a7fccf2d22.png)

This goes back to my initial post^, where I talked about the weird behavior being seemingly related to the number of plugins installed rather than which plugins are installed. If I gradually re-add plugins to this clean server, eventually Orebfuscator starts crashing & ProtocolLib breaks with it. No individual plugin seems to be responsible: I will add plugins until it breaks, then remove the plugin that broke the server and add another and it will still break, around ~47 plugins installed. 

I'm not convinced that it is an issue with Orebfuscator at this point, because it seems like Orebfuscator runs fine when fewer plugins are installed, whichever they are. I don't really know whats going on here but I think if I just remove some of the extra plugins I don't need as much, I can find some combination in which everything runs. If at any point I gain more insight into this whole weird phenomenon I will keep you posted! Thank you for helping me with this craziness.

**Comment by Ingrim4** [comment]
Closed due to inactivity and no progress towards resolving the issue.
