### ISSUE TITLE
Minecart BUG

### ISSUE THREAD

**Issue by CelaldoganGunes** [Imprex-Development/orebfuscator#83]
Server Version: git-Paper-342 MC 1.16.4 API Version 1.16.4-R0.1
Orebfuscator Version: 5.1.3
Protocollib Version: 4.5.1

Describe the bug:
Plugin doesn't hide minecarts. XRAY users can find mineshafts if they close every block in hack settings. Because they can see minecarts.

**Comment by Ingrim4** [comment]
Hiding entities isn't part of Orebfuscator and we do not plane to add that.
