### ISSUE TITLE
Always getting error that says orebfuscator bypassed

### ISSUE THREAD

**Issue by Grolicek** [Imprex-Development/orebfuscator#84]
**Please fill out the following information:**

* Server Version: <1.16.4 spigot>
* Orebfuscator Version: <5.1.3>
* Protocollib Version: <4.5.1>

as said in tittle and no commands works

maybe join my server? to see idk other how to...

**Comment by Ingrim4** [comment]
If by error you mean a chat message telling you that you bypassed orebfuscator that's intended behavior. This message is just telling you that you won't receive any obfuscated chunks. You can disable this message in the config under [general.bypassNotification](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#general).

**Comment by Grolicek** [comment]
Yea but xray is still possible to use also by non op players so idk where i have problem can u help me please?

**Comment by Grolicek** [comment]
Sorry my bad, i have wrong world names so it didn't work. I got that idea from that link! Thanks much
