### ISSUE TITLE
Prior releases included a way to ask Orebfuscator to update a Location, is there any equivalent or can one be added?

### ISSUE THREAD

**Issue by ProgrammerDan** [Imprex-Development/orebfuscator#85]
Previously, an API was exposed for integration purposes. The "BlockUpdate" api could be used to inform Orebfuscator to recompute a block; for instance, in HiddenOre we alter blocks and a compatibility layer would sent BlockUpdate.updateByLocations() a list of locations that were altered, and Orebfuscator would recompute.

Anyway, wasn't able to find an equiv in the current version, and wasn't sure what path to take. Thanks!

**Comment by Ingrim4** [comment]
As of now there is no way to achieve what you want. I do have plans to add a simple API for that but still have some concerns regarding the performance impact of calling that method. I probably need to improve the update concept a bit.

**Comment by ProgrammerDan** [comment]
Thanks for the reply! Definitely will be useful in some contexts. In prior
incarnations we'd implemented it as a "pass in a list of locations" to
optimize for performance, so the calling plugin could aggregate a list of
blocks needing updates and handle them at once.

Regardless, I'll wait and see what you come up with, whenever you get time
for it. Thanks again.

**Comment by Ingrim4** [comment]
Here is a first preview: https://github.com/Imprex-Development/Orebfuscator/tree/85-api

**Comment by ProgrammerDan** [comment]
You guys rock -- love the API add and amazing bonus to have an example
distributed with it as well. Thank you.
