### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by Ingrim4** [Imprex-Development/orebfuscator#96]
Prepare project for update to 1.17

**Comment by akiselevprivate** [comment]
Any updates?

**Comment by NgLoader** [comment]
Waiting for the 1.17 release
[Current 1.17 Branch](https://github.com/Imprex-Development/Orebfuscator/tree/96-1.17)

**Comment by Andarius68** [comment]
It won't load on Spigot 1.17 now.

**Comment by NgLoader** [comment]
@Andarius68 The currently branch is a testing branch and currently in progress, there is no release or pre release!

**Comment by Andarius68** [comment]
Thank you.
